// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface AndroidSdkSyspropGuardConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.AndroidSdkSyspropGuardConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If true, configures SurfaceFlinger to initialize Skia's Perfetto
   * integration with the track_event data source in RenderEngine.
   * If false or omitted, the simpler ATrace fallback is used.
   * NOTE: once enabled, Skia will only revert to ATrace if SurfaceFlinger is
   * restarted.
   * Specifically this sets the following system properties:
   *   - debug.tracing.ctl.renderengine.skia_tracing_enabled
   *   - debug.tracing.ctl.renderengine.skia_use_perfetto_track_events
   * Does not affect actual track_event data *collection*, which must be
   * configured separately.
   * </pre>
   *
   * <code>optional bool surfaceflinger_skia_track_events = 1;</code>
   * @return Whether the surfaceflingerSkiaTrackEvents field is set.
   */
  boolean hasSurfaceflingerSkiaTrackEvents();
  /**
   * <pre>
   * If true, configures SurfaceFlinger to initialize Skia's Perfetto
   * integration with the track_event data source in RenderEngine.
   * If false or omitted, the simpler ATrace fallback is used.
   * NOTE: once enabled, Skia will only revert to ATrace if SurfaceFlinger is
   * restarted.
   * Specifically this sets the following system properties:
   *   - debug.tracing.ctl.renderengine.skia_tracing_enabled
   *   - debug.tracing.ctl.renderengine.skia_use_perfetto_track_events
   * Does not affect actual track_event data *collection*, which must be
   * configured separately.
   * </pre>
   *
   * <code>optional bool surfaceflinger_skia_track_events = 1;</code>
   * @return The surfaceflingerSkiaTrackEvents.
   */
  boolean getSurfaceflingerSkiaTrackEvents();

  /**
   * <pre>
   * If true, configures HWUI apps to initialize Skia's Perfetto integration
   * with the track_event data source. hwui_package_name_filter
   * can be used to control which apps are affected.
   * If false or omitted, the simpler ATrace fallback is used.
   * NOTE: once enabled, Skia will only revert to ATrace if the app is
   * restarted.
   * ATTENTION: affects ALL HWUI APPS if hwui_package_name_filter is not set!
   * If filtering is NOT set, this controls these GLOBAL system properties:
   *   - debug.tracing.ctl.hwui.skia_tracing_enabled
   *   - debug.tracing.ctl.hwui.skia_use_perfetto_track_events
   * If filtering IS set, this controls these APP-SPECIFIC system properties,
   * for each package listed in the filter:
   *   - debug.tracing.ctl.hwui.skia_tracing_enabled.&lt;package.name&gt;
   *   - debug.tracing.ctl.hwui.skia_use_perfetto_track_events.&lt;package.name&gt;
   * Does not affect actual track_event data *collection*, which must be
   * configured separately.
   * </pre>
   *
   * <code>optional bool hwui_skia_track_events = 2;</code>
   * @return Whether the hwuiSkiaTrackEvents field is set.
   */
  boolean hasHwuiSkiaTrackEvents();
  /**
   * <pre>
   * If true, configures HWUI apps to initialize Skia's Perfetto integration
   * with the track_event data source. hwui_package_name_filter
   * can be used to control which apps are affected.
   * If false or omitted, the simpler ATrace fallback is used.
   * NOTE: once enabled, Skia will only revert to ATrace if the app is
   * restarted.
   * ATTENTION: affects ALL HWUI APPS if hwui_package_name_filter is not set!
   * If filtering is NOT set, this controls these GLOBAL system properties:
   *   - debug.tracing.ctl.hwui.skia_tracing_enabled
   *   - debug.tracing.ctl.hwui.skia_use_perfetto_track_events
   * If filtering IS set, this controls these APP-SPECIFIC system properties,
   * for each package listed in the filter:
   *   - debug.tracing.ctl.hwui.skia_tracing_enabled.&lt;package.name&gt;
   *   - debug.tracing.ctl.hwui.skia_use_perfetto_track_events.&lt;package.name&gt;
   * Does not affect actual track_event data *collection*, which must be
   * configured separately.
   * </pre>
   *
   * <code>optional bool hwui_skia_track_events = 2;</code>
   * @return The hwuiSkiaTrackEvents.
   */
  boolean getHwuiSkiaTrackEvents();

  /**
   * <pre>
   * If non-empty, hwui_skia_track_events applies to only the packages listed.
   * Otherwise, hwui_skia_track_events applies globally to all HWUI apps.
   * </pre>
   *
   * <code>repeated string hwui_package_name_filter = 3;</code>
   * @return A list containing the hwuiPackageNameFilter.
   */
  java.util.List<java.lang.String>
      getHwuiPackageNameFilterList();
  /**
   * <pre>
   * If non-empty, hwui_skia_track_events applies to only the packages listed.
   * Otherwise, hwui_skia_track_events applies globally to all HWUI apps.
   * </pre>
   *
   * <code>repeated string hwui_package_name_filter = 3;</code>
   * @return The count of hwuiPackageNameFilter.
   */
  int getHwuiPackageNameFilterCount();
  /**
   * <pre>
   * If non-empty, hwui_skia_track_events applies to only the packages listed.
   * Otherwise, hwui_skia_track_events applies globally to all HWUI apps.
   * </pre>
   *
   * <code>repeated string hwui_package_name_filter = 3;</code>
   * @param index The index of the element to return.
   * @return The hwuiPackageNameFilter at the given index.
   */
  java.lang.String getHwuiPackageNameFilter(int index);
  /**
   * <pre>
   * If non-empty, hwui_skia_track_events applies to only the packages listed.
   * Otherwise, hwui_skia_track_events applies globally to all HWUI apps.
   * </pre>
   *
   * <code>repeated string hwui_package_name_filter = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hwuiPackageNameFilter at the given index.
   */
  com.google.protobuf.ByteString
      getHwuiPackageNameFilterBytes(int index);
}
