// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.AndroidEnergyConsumerDescriptor}
 */
public final class AndroidEnergyConsumerDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.AndroidEnergyConsumerDescriptor)
    AndroidEnergyConsumerDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AndroidEnergyConsumerDescriptor.newBuilder() to construct.
  private AndroidEnergyConsumerDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AndroidEnergyConsumerDescriptor() {
    energyConsumers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AndroidEnergyConsumerDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.AndroidEnergyConsumerDescriptor.class, perfetto.protos.AndroidEnergyConsumerDescriptor.Builder.class);
  }

  public static final int ENERGY_CONSUMERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<perfetto.protos.AndroidEnergyConsumer> energyConsumers_;
  /**
   * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<perfetto.protos.AndroidEnergyConsumer> getEnergyConsumersList() {
    return energyConsumers_;
  }
  /**
   * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends perfetto.protos.AndroidEnergyConsumerOrBuilder> 
      getEnergyConsumersOrBuilderList() {
    return energyConsumers_;
  }
  /**
   * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
   */
  @java.lang.Override
  public int getEnergyConsumersCount() {
    return energyConsumers_.size();
  }
  /**
   * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
   */
  @java.lang.Override
  public perfetto.protos.AndroidEnergyConsumer getEnergyConsumers(int index) {
    return energyConsumers_.get(index);
  }
  /**
   * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
   */
  @java.lang.Override
  public perfetto.protos.AndroidEnergyConsumerOrBuilder getEnergyConsumersOrBuilder(
      int index) {
    return energyConsumers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < energyConsumers_.size(); i++) {
      output.writeMessage(1, energyConsumers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < energyConsumers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, energyConsumers_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.AndroidEnergyConsumerDescriptor)) {
      return super.equals(obj);
    }
    perfetto.protos.AndroidEnergyConsumerDescriptor other = (perfetto.protos.AndroidEnergyConsumerDescriptor) obj;

    if (!getEnergyConsumersList()
        .equals(other.getEnergyConsumersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEnergyConsumersCount() > 0) {
      hash = (37 * hash) + ENERGY_CONSUMERS_FIELD_NUMBER;
      hash = (53 * hash) + getEnergyConsumersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.AndroidEnergyConsumerDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.AndroidEnergyConsumerDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.AndroidEnergyConsumerDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.AndroidEnergyConsumerDescriptor)
      perfetto.protos.AndroidEnergyConsumerDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.AndroidEnergyConsumerDescriptor.class, perfetto.protos.AndroidEnergyConsumerDescriptor.Builder.class);
    }

    // Construct using perfetto.protos.AndroidEnergyConsumerDescriptor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (energyConsumersBuilder_ == null) {
        energyConsumers_ = java.util.Collections.emptyList();
      } else {
        energyConsumers_ = null;
        energyConsumersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptor getDefaultInstanceForType() {
      return perfetto.protos.AndroidEnergyConsumerDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptor build() {
      perfetto.protos.AndroidEnergyConsumerDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptor buildPartial() {
      perfetto.protos.AndroidEnergyConsumerDescriptor result = new perfetto.protos.AndroidEnergyConsumerDescriptor(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(perfetto.protos.AndroidEnergyConsumerDescriptor result) {
      if (energyConsumersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          energyConsumers_ = java.util.Collections.unmodifiableList(energyConsumers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.energyConsumers_ = energyConsumers_;
      } else {
        result.energyConsumers_ = energyConsumersBuilder_.build();
      }
    }

    private void buildPartial0(perfetto.protos.AndroidEnergyConsumerDescriptor result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.AndroidEnergyConsumerDescriptor) {
        return mergeFrom((perfetto.protos.AndroidEnergyConsumerDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.AndroidEnergyConsumerDescriptor other) {
      if (other == perfetto.protos.AndroidEnergyConsumerDescriptor.getDefaultInstance()) return this;
      if (energyConsumersBuilder_ == null) {
        if (!other.energyConsumers_.isEmpty()) {
          if (energyConsumers_.isEmpty()) {
            energyConsumers_ = other.energyConsumers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEnergyConsumersIsMutable();
            energyConsumers_.addAll(other.energyConsumers_);
          }
          onChanged();
        }
      } else {
        if (!other.energyConsumers_.isEmpty()) {
          if (energyConsumersBuilder_.isEmpty()) {
            energyConsumersBuilder_.dispose();
            energyConsumersBuilder_ = null;
            energyConsumers_ = other.energyConsumers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            energyConsumersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEnergyConsumersFieldBuilder() : null;
          } else {
            energyConsumersBuilder_.addAllMessages(other.energyConsumers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              perfetto.protos.AndroidEnergyConsumer m =
                  input.readMessage(
                      perfetto.protos.AndroidEnergyConsumer.PARSER,
                      extensionRegistry);
              if (energyConsumersBuilder_ == null) {
                ensureEnergyConsumersIsMutable();
                energyConsumers_.add(m);
              } else {
                energyConsumersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<perfetto.protos.AndroidEnergyConsumer> energyConsumers_ =
      java.util.Collections.emptyList();
    private void ensureEnergyConsumersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        energyConsumers_ = new java.util.ArrayList<perfetto.protos.AndroidEnergyConsumer>(energyConsumers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        perfetto.protos.AndroidEnergyConsumer, perfetto.protos.AndroidEnergyConsumer.Builder, perfetto.protos.AndroidEnergyConsumerOrBuilder> energyConsumersBuilder_;

    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public java.util.List<perfetto.protos.AndroidEnergyConsumer> getEnergyConsumersList() {
      if (energyConsumersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(energyConsumers_);
      } else {
        return energyConsumersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public int getEnergyConsumersCount() {
      if (energyConsumersBuilder_ == null) {
        return energyConsumers_.size();
      } else {
        return energyConsumersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public perfetto.protos.AndroidEnergyConsumer getEnergyConsumers(int index) {
      if (energyConsumersBuilder_ == null) {
        return energyConsumers_.get(index);
      } else {
        return energyConsumersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder setEnergyConsumers(
        int index, perfetto.protos.AndroidEnergyConsumer value) {
      if (energyConsumersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnergyConsumersIsMutable();
        energyConsumers_.set(index, value);
        onChanged();
      } else {
        energyConsumersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder setEnergyConsumers(
        int index, perfetto.protos.AndroidEnergyConsumer.Builder builderForValue) {
      if (energyConsumersBuilder_ == null) {
        ensureEnergyConsumersIsMutable();
        energyConsumers_.set(index, builderForValue.build());
        onChanged();
      } else {
        energyConsumersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder addEnergyConsumers(perfetto.protos.AndroidEnergyConsumer value) {
      if (energyConsumersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnergyConsumersIsMutable();
        energyConsumers_.add(value);
        onChanged();
      } else {
        energyConsumersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder addEnergyConsumers(
        int index, perfetto.protos.AndroidEnergyConsumer value) {
      if (energyConsumersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnergyConsumersIsMutable();
        energyConsumers_.add(index, value);
        onChanged();
      } else {
        energyConsumersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder addEnergyConsumers(
        perfetto.protos.AndroidEnergyConsumer.Builder builderForValue) {
      if (energyConsumersBuilder_ == null) {
        ensureEnergyConsumersIsMutable();
        energyConsumers_.add(builderForValue.build());
        onChanged();
      } else {
        energyConsumersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder addEnergyConsumers(
        int index, perfetto.protos.AndroidEnergyConsumer.Builder builderForValue) {
      if (energyConsumersBuilder_ == null) {
        ensureEnergyConsumersIsMutable();
        energyConsumers_.add(index, builderForValue.build());
        onChanged();
      } else {
        energyConsumersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder addAllEnergyConsumers(
        java.lang.Iterable<? extends perfetto.protos.AndroidEnergyConsumer> values) {
      if (energyConsumersBuilder_ == null) {
        ensureEnergyConsumersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, energyConsumers_);
        onChanged();
      } else {
        energyConsumersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder clearEnergyConsumers() {
      if (energyConsumersBuilder_ == null) {
        energyConsumers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        energyConsumersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public Builder removeEnergyConsumers(int index) {
      if (energyConsumersBuilder_ == null) {
        ensureEnergyConsumersIsMutable();
        energyConsumers_.remove(index);
        onChanged();
      } else {
        energyConsumersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public perfetto.protos.AndroidEnergyConsumer.Builder getEnergyConsumersBuilder(
        int index) {
      return getEnergyConsumersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public perfetto.protos.AndroidEnergyConsumerOrBuilder getEnergyConsumersOrBuilder(
        int index) {
      if (energyConsumersBuilder_ == null) {
        return energyConsumers_.get(index);  } else {
        return energyConsumersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public java.util.List<? extends perfetto.protos.AndroidEnergyConsumerOrBuilder> 
         getEnergyConsumersOrBuilderList() {
      if (energyConsumersBuilder_ != null) {
        return energyConsumersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(energyConsumers_);
      }
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public perfetto.protos.AndroidEnergyConsumer.Builder addEnergyConsumersBuilder() {
      return getEnergyConsumersFieldBuilder().addBuilder(
          perfetto.protos.AndroidEnergyConsumer.getDefaultInstance());
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public perfetto.protos.AndroidEnergyConsumer.Builder addEnergyConsumersBuilder(
        int index) {
      return getEnergyConsumersFieldBuilder().addBuilder(
          index, perfetto.protos.AndroidEnergyConsumer.getDefaultInstance());
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    public java.util.List<perfetto.protos.AndroidEnergyConsumer.Builder> 
         getEnergyConsumersBuilderList() {
      return getEnergyConsumersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        perfetto.protos.AndroidEnergyConsumer, perfetto.protos.AndroidEnergyConsumer.Builder, perfetto.protos.AndroidEnergyConsumerOrBuilder> 
        getEnergyConsumersFieldBuilder() {
      if (energyConsumersBuilder_ == null) {
        energyConsumersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            perfetto.protos.AndroidEnergyConsumer, perfetto.protos.AndroidEnergyConsumer.Builder, perfetto.protos.AndroidEnergyConsumerOrBuilder>(
                energyConsumers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        energyConsumers_ = null;
      }
      return energyConsumersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.AndroidEnergyConsumerDescriptor)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidEnergyConsumerDescriptor)
  private static final perfetto.protos.AndroidEnergyConsumerDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.AndroidEnergyConsumerDescriptor();
  }

  public static perfetto.protos.AndroidEnergyConsumerDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AndroidEnergyConsumerDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<AndroidEnergyConsumerDescriptor>() {
    @java.lang.Override
    public AndroidEnergyConsumerDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AndroidEnergyConsumerDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AndroidEnergyConsumerDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.AndroidEnergyConsumerDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

