// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface BeginFrameObserverStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.BeginFrameObserverState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 dropped_begin_frame_args = 1;</code>
   * @return Whether the droppedBeginFrameArgs field is set.
   */
  boolean hasDroppedBeginFrameArgs();
  /**
   * <code>optional int64 dropped_begin_frame_args = 1;</code>
   * @return The droppedBeginFrameArgs.
   */
  long getDroppedBeginFrameArgs();

  /**
   * <code>optional .perfetto.protos.BeginFrameArgs last_begin_frame_args = 2;</code>
   * @return Whether the lastBeginFrameArgs field is set.
   */
  boolean hasLastBeginFrameArgs();
  /**
   * <code>optional .perfetto.protos.BeginFrameArgs last_begin_frame_args = 2;</code>
   * @return The lastBeginFrameArgs.
   */
  perfetto.protos.BeginFrameArgs getLastBeginFrameArgs();
  /**
   * <code>optional .perfetto.protos.BeginFrameArgs last_begin_frame_args = 2;</code>
   */
  perfetto.protos.BeginFrameArgsOrBuilder getLastBeginFrameArgsOrBuilder();
}
