// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.DeobfuscationMapping}
 */
public final class DeobfuscationMapping extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.DeobfuscationMapping)
    DeobfuscationMappingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeobfuscationMapping.newBuilder() to construct.
  private DeobfuscationMapping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeobfuscationMapping() {
    packageName_ = "";
    obfuscatedClasses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeobfuscationMapping();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_DeobfuscationMapping_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_DeobfuscationMapping_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.DeobfuscationMapping.class, perfetto.protos.DeobfuscationMapping.Builder.class);
  }

  private int bitField0_;
  public static final int PACKAGE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packageName_ = "";
  /**
   * <code>optional string package_name = 1;</code>
   * @return Whether the packageName field is set.
   */
  @java.lang.Override
  public boolean hasPackageName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string package_name = 1;</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        packageName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string package_name = 1;</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_CODE_FIELD_NUMBER = 2;
  private long versionCode_ = 0L;
  /**
   * <code>optional int64 version_code = 2;</code>
   * @return Whether the versionCode field is set.
   */
  @java.lang.Override
  public boolean hasVersionCode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 version_code = 2;</code>
   * @return The versionCode.
   */
  @java.lang.Override
  public long getVersionCode() {
    return versionCode_;
  }

  public static final int OBFUSCATED_CLASSES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<perfetto.protos.ObfuscatedClass> obfuscatedClasses_;
  /**
   * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<perfetto.protos.ObfuscatedClass> getObfuscatedClassesList() {
    return obfuscatedClasses_;
  }
  /**
   * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends perfetto.protos.ObfuscatedClassOrBuilder> 
      getObfuscatedClassesOrBuilderList() {
    return obfuscatedClasses_;
  }
  /**
   * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
   */
  @java.lang.Override
  public int getObfuscatedClassesCount() {
    return obfuscatedClasses_.size();
  }
  /**
   * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
   */
  @java.lang.Override
  public perfetto.protos.ObfuscatedClass getObfuscatedClasses(int index) {
    return obfuscatedClasses_.get(index);
  }
  /**
   * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
   */
  @java.lang.Override
  public perfetto.protos.ObfuscatedClassOrBuilder getObfuscatedClassesOrBuilder(
      int index) {
    return obfuscatedClasses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, packageName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, versionCode_);
    }
    for (int i = 0; i < obfuscatedClasses_.size(); i++) {
      output.writeMessage(3, obfuscatedClasses_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, packageName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, versionCode_);
    }
    for (int i = 0; i < obfuscatedClasses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, obfuscatedClasses_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.DeobfuscationMapping)) {
      return super.equals(obj);
    }
    perfetto.protos.DeobfuscationMapping other = (perfetto.protos.DeobfuscationMapping) obj;

    if (hasPackageName() != other.hasPackageName()) return false;
    if (hasPackageName()) {
      if (!getPackageName()
          .equals(other.getPackageName())) return false;
    }
    if (hasVersionCode() != other.hasVersionCode()) return false;
    if (hasVersionCode()) {
      if (getVersionCode()
          != other.getVersionCode()) return false;
    }
    if (!getObfuscatedClassesList()
        .equals(other.getObfuscatedClassesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPackageName()) {
      hash = (37 * hash) + PACKAGE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPackageName().hashCode();
    }
    if (hasVersionCode()) {
      hash = (37 * hash) + VERSION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersionCode());
    }
    if (getObfuscatedClassesCount() > 0) {
      hash = (37 * hash) + OBFUSCATED_CLASSES_FIELD_NUMBER;
      hash = (53 * hash) + getObfuscatedClassesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.DeobfuscationMapping parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.DeobfuscationMapping parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.DeobfuscationMapping parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.DeobfuscationMapping parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.DeobfuscationMapping prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.DeobfuscationMapping}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.DeobfuscationMapping)
      perfetto.protos.DeobfuscationMappingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_DeobfuscationMapping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_DeobfuscationMapping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.DeobfuscationMapping.class, perfetto.protos.DeobfuscationMapping.Builder.class);
    }

    // Construct using perfetto.protos.DeobfuscationMapping.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      packageName_ = "";
      versionCode_ = 0L;
      if (obfuscatedClassesBuilder_ == null) {
        obfuscatedClasses_ = java.util.Collections.emptyList();
      } else {
        obfuscatedClasses_ = null;
        obfuscatedClassesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_DeobfuscationMapping_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.DeobfuscationMapping getDefaultInstanceForType() {
      return perfetto.protos.DeobfuscationMapping.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.DeobfuscationMapping build() {
      perfetto.protos.DeobfuscationMapping result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.DeobfuscationMapping buildPartial() {
      perfetto.protos.DeobfuscationMapping result = new perfetto.protos.DeobfuscationMapping(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(perfetto.protos.DeobfuscationMapping result) {
      if (obfuscatedClassesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          obfuscatedClasses_ = java.util.Collections.unmodifiableList(obfuscatedClasses_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.obfuscatedClasses_ = obfuscatedClasses_;
      } else {
        result.obfuscatedClasses_ = obfuscatedClassesBuilder_.build();
      }
    }

    private void buildPartial0(perfetto.protos.DeobfuscationMapping result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.packageName_ = packageName_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.versionCode_ = versionCode_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.DeobfuscationMapping) {
        return mergeFrom((perfetto.protos.DeobfuscationMapping)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.DeobfuscationMapping other) {
      if (other == perfetto.protos.DeobfuscationMapping.getDefaultInstance()) return this;
      if (other.hasPackageName()) {
        packageName_ = other.packageName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasVersionCode()) {
        setVersionCode(other.getVersionCode());
      }
      if (obfuscatedClassesBuilder_ == null) {
        if (!other.obfuscatedClasses_.isEmpty()) {
          if (obfuscatedClasses_.isEmpty()) {
            obfuscatedClasses_ = other.obfuscatedClasses_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureObfuscatedClassesIsMutable();
            obfuscatedClasses_.addAll(other.obfuscatedClasses_);
          }
          onChanged();
        }
      } else {
        if (!other.obfuscatedClasses_.isEmpty()) {
          if (obfuscatedClassesBuilder_.isEmpty()) {
            obfuscatedClassesBuilder_.dispose();
            obfuscatedClassesBuilder_ = null;
            obfuscatedClasses_ = other.obfuscatedClasses_;
            bitField0_ = (bitField0_ & ~0x00000004);
            obfuscatedClassesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getObfuscatedClassesFieldBuilder() : null;
          } else {
            obfuscatedClassesBuilder_.addAllMessages(other.obfuscatedClasses_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              packageName_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              versionCode_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              perfetto.protos.ObfuscatedClass m =
                  input.readMessage(
                      perfetto.protos.ObfuscatedClass.PARSER,
                      extensionRegistry);
              if (obfuscatedClassesBuilder_ == null) {
                ensureObfuscatedClassesIsMutable();
                obfuscatedClasses_.add(m);
              } else {
                obfuscatedClassesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object packageName_ = "";
    /**
     * <code>optional string package_name = 1;</code>
     * @return Whether the packageName field is set.
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string package_name = 1;</code>
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string package_name = 1;</code>
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string package_name = 1;</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packageName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      packageName_ = getDefaultInstance().getPackageName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_name = 1;</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      packageName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long versionCode_ ;
    /**
     * <code>optional int64 version_code = 2;</code>
     * @return Whether the versionCode field is set.
     */
    @java.lang.Override
    public boolean hasVersionCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 version_code = 2;</code>
     * @return The versionCode.
     */
    @java.lang.Override
    public long getVersionCode() {
      return versionCode_;
    }
    /**
     * <code>optional int64 version_code = 2;</code>
     * @param value The versionCode to set.
     * @return This builder for chaining.
     */
    public Builder setVersionCode(long value) {
      
      versionCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 version_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersionCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      versionCode_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<perfetto.protos.ObfuscatedClass> obfuscatedClasses_ =
      java.util.Collections.emptyList();
    private void ensureObfuscatedClassesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        obfuscatedClasses_ = new java.util.ArrayList<perfetto.protos.ObfuscatedClass>(obfuscatedClasses_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        perfetto.protos.ObfuscatedClass, perfetto.protos.ObfuscatedClass.Builder, perfetto.protos.ObfuscatedClassOrBuilder> obfuscatedClassesBuilder_;

    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public java.util.List<perfetto.protos.ObfuscatedClass> getObfuscatedClassesList() {
      if (obfuscatedClassesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(obfuscatedClasses_);
      } else {
        return obfuscatedClassesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public int getObfuscatedClassesCount() {
      if (obfuscatedClassesBuilder_ == null) {
        return obfuscatedClasses_.size();
      } else {
        return obfuscatedClassesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public perfetto.protos.ObfuscatedClass getObfuscatedClasses(int index) {
      if (obfuscatedClassesBuilder_ == null) {
        return obfuscatedClasses_.get(index);
      } else {
        return obfuscatedClassesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder setObfuscatedClasses(
        int index, perfetto.protos.ObfuscatedClass value) {
      if (obfuscatedClassesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.set(index, value);
        onChanged();
      } else {
        obfuscatedClassesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder setObfuscatedClasses(
        int index, perfetto.protos.ObfuscatedClass.Builder builderForValue) {
      if (obfuscatedClassesBuilder_ == null) {
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.set(index, builderForValue.build());
        onChanged();
      } else {
        obfuscatedClassesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder addObfuscatedClasses(perfetto.protos.ObfuscatedClass value) {
      if (obfuscatedClassesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.add(value);
        onChanged();
      } else {
        obfuscatedClassesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder addObfuscatedClasses(
        int index, perfetto.protos.ObfuscatedClass value) {
      if (obfuscatedClassesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.add(index, value);
        onChanged();
      } else {
        obfuscatedClassesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder addObfuscatedClasses(
        perfetto.protos.ObfuscatedClass.Builder builderForValue) {
      if (obfuscatedClassesBuilder_ == null) {
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.add(builderForValue.build());
        onChanged();
      } else {
        obfuscatedClassesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder addObfuscatedClasses(
        int index, perfetto.protos.ObfuscatedClass.Builder builderForValue) {
      if (obfuscatedClassesBuilder_ == null) {
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.add(index, builderForValue.build());
        onChanged();
      } else {
        obfuscatedClassesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder addAllObfuscatedClasses(
        java.lang.Iterable<? extends perfetto.protos.ObfuscatedClass> values) {
      if (obfuscatedClassesBuilder_ == null) {
        ensureObfuscatedClassesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, obfuscatedClasses_);
        onChanged();
      } else {
        obfuscatedClassesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder clearObfuscatedClasses() {
      if (obfuscatedClassesBuilder_ == null) {
        obfuscatedClasses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        obfuscatedClassesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public Builder removeObfuscatedClasses(int index) {
      if (obfuscatedClassesBuilder_ == null) {
        ensureObfuscatedClassesIsMutable();
        obfuscatedClasses_.remove(index);
        onChanged();
      } else {
        obfuscatedClassesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public perfetto.protos.ObfuscatedClass.Builder getObfuscatedClassesBuilder(
        int index) {
      return getObfuscatedClassesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public perfetto.protos.ObfuscatedClassOrBuilder getObfuscatedClassesOrBuilder(
        int index) {
      if (obfuscatedClassesBuilder_ == null) {
        return obfuscatedClasses_.get(index);  } else {
        return obfuscatedClassesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public java.util.List<? extends perfetto.protos.ObfuscatedClassOrBuilder> 
         getObfuscatedClassesOrBuilderList() {
      if (obfuscatedClassesBuilder_ != null) {
        return obfuscatedClassesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(obfuscatedClasses_);
      }
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public perfetto.protos.ObfuscatedClass.Builder addObfuscatedClassesBuilder() {
      return getObfuscatedClassesFieldBuilder().addBuilder(
          perfetto.protos.ObfuscatedClass.getDefaultInstance());
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public perfetto.protos.ObfuscatedClass.Builder addObfuscatedClassesBuilder(
        int index) {
      return getObfuscatedClassesFieldBuilder().addBuilder(
          index, perfetto.protos.ObfuscatedClass.getDefaultInstance());
    }
    /**
     * <code>repeated .perfetto.protos.ObfuscatedClass obfuscated_classes = 3;</code>
     */
    public java.util.List<perfetto.protos.ObfuscatedClass.Builder> 
         getObfuscatedClassesBuilderList() {
      return getObfuscatedClassesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        perfetto.protos.ObfuscatedClass, perfetto.protos.ObfuscatedClass.Builder, perfetto.protos.ObfuscatedClassOrBuilder> 
        getObfuscatedClassesFieldBuilder() {
      if (obfuscatedClassesBuilder_ == null) {
        obfuscatedClassesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            perfetto.protos.ObfuscatedClass, perfetto.protos.ObfuscatedClass.Builder, perfetto.protos.ObfuscatedClassOrBuilder>(
                obfuscatedClasses_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        obfuscatedClasses_ = null;
      }
      return obfuscatedClassesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.DeobfuscationMapping)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.DeobfuscationMapping)
  private static final perfetto.protos.DeobfuscationMapping DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.DeobfuscationMapping();
  }

  public static perfetto.protos.DeobfuscationMapping getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DeobfuscationMapping>
      PARSER = new com.google.protobuf.AbstractParser<DeobfuscationMapping>() {
    @java.lang.Override
    public DeobfuscationMapping parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeobfuscationMapping> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeobfuscationMapping> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.DeobfuscationMapping getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

