// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface EventCategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.EventCategory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 iid = 1;</code>
   * @return Whether the iid field is set.
   */
  boolean hasIid();
  /**
   * <code>optional uint64 iid = 1;</code>
   * @return The iid.
   */
  long getIid();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
