// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.Ext4MbReleaseInodePaFtraceEvent}
 */
public final class Ext4MbReleaseInodePaFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.Ext4MbReleaseInodePaFtraceEvent)
    Ext4MbReleaseInodePaFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ext4MbReleaseInodePaFtraceEvent.newBuilder() to construct.
  private Ext4MbReleaseInodePaFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ext4MbReleaseInodePaFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ext4MbReleaseInodePaFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MbReleaseInodePaFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MbReleaseInodePaFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.class, perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int DEV_FIELD_NUMBER = 1;
  private long dev_ = 0L;
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return Whether the dev field is set.
   */
  @java.lang.Override
  public boolean hasDev() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return The dev.
   */
  @java.lang.Override
  public long getDev() {
    return dev_;
  }

  public static final int INO_FIELD_NUMBER = 2;
  private long ino_ = 0L;
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return Whether the ino field is set.
   */
  @java.lang.Override
  public boolean hasIno() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return The ino.
   */
  @java.lang.Override
  public long getIno() {
    return ino_;
  }

  public static final int BLOCK_FIELD_NUMBER = 3;
  private long block_ = 0L;
  /**
   * <code>optional uint64 block = 3;</code>
   * @return Whether the block field is set.
   */
  @java.lang.Override
  public boolean hasBlock() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint64 block = 3;</code>
   * @return The block.
   */
  @java.lang.Override
  public long getBlock() {
    return block_;
  }

  public static final int COUNT_FIELD_NUMBER = 4;
  private int count_ = 0;
  /**
   * <code>optional uint32 count = 4;</code>
   * @return Whether the count field is set.
   */
  @java.lang.Override
  public boolean hasCount() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint32 count = 4;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, dev_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt64(2, ino_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt64(3, block_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt32(4, count_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, dev_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, ino_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, block_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, count_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.Ext4MbReleaseInodePaFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.Ext4MbReleaseInodePaFtraceEvent other = (perfetto.protos.Ext4MbReleaseInodePaFtraceEvent) obj;

    if (hasDev() != other.hasDev()) return false;
    if (hasDev()) {
      if (getDev()
          != other.getDev()) return false;
    }
    if (hasIno() != other.hasIno()) return false;
    if (hasIno()) {
      if (getIno()
          != other.getIno()) return false;
    }
    if (hasBlock() != other.hasBlock()) return false;
    if (hasBlock()) {
      if (getBlock()
          != other.getBlock()) return false;
    }
    if (hasCount() != other.hasCount()) return false;
    if (hasCount()) {
      if (getCount()
          != other.getCount()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDev()) {
      hash = (37 * hash) + DEV_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDev());
    }
    if (hasIno()) {
      hash = (37 * hash) + INO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIno());
    }
    if (hasBlock()) {
      hash = (37 * hash) + BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlock());
    }
    if (hasCount()) {
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.Ext4MbReleaseInodePaFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.Ext4MbReleaseInodePaFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.Ext4MbReleaseInodePaFtraceEvent)
      perfetto.protos.Ext4MbReleaseInodePaFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MbReleaseInodePaFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MbReleaseInodePaFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.class, perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dev_ = 0L;
      ino_ = 0L;
      block_ = 0L;
      count_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MbReleaseInodePaFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.Ext4MbReleaseInodePaFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.Ext4MbReleaseInodePaFtraceEvent build() {
      perfetto.protos.Ext4MbReleaseInodePaFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.Ext4MbReleaseInodePaFtraceEvent buildPartial() {
      perfetto.protos.Ext4MbReleaseInodePaFtraceEvent result = new perfetto.protos.Ext4MbReleaseInodePaFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.Ext4MbReleaseInodePaFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dev_ = dev_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ino_ = ino_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.block_ = block_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.count_ = count_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.Ext4MbReleaseInodePaFtraceEvent) {
        return mergeFrom((perfetto.protos.Ext4MbReleaseInodePaFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.Ext4MbReleaseInodePaFtraceEvent other) {
      if (other == perfetto.protos.Ext4MbReleaseInodePaFtraceEvent.getDefaultInstance()) return this;
      if (other.hasDev()) {
        setDev(other.getDev());
      }
      if (other.hasIno()) {
        setIno(other.getIno());
      }
      if (other.hasBlock()) {
        setBlock(other.getBlock());
      }
      if (other.hasCount()) {
        setCount(other.getCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              dev_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              ino_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              block_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              count_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long dev_ ;
    /**
     * <code>optional uint64 dev = 1;</code>
     * @return Whether the dev field is set.
     */
    @java.lang.Override
    public boolean hasDev() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 dev = 1;</code>
     * @return The dev.
     */
    @java.lang.Override
    public long getDev() {
      return dev_;
    }
    /**
     * <code>optional uint64 dev = 1;</code>
     * @param value The dev to set.
     * @return This builder for chaining.
     */
    public Builder setDev(long value) {
      
      dev_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 dev = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDev() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dev_ = 0L;
      onChanged();
      return this;
    }

    private long ino_ ;
    /**
     * <code>optional uint64 ino = 2;</code>
     * @return Whether the ino field is set.
     */
    @java.lang.Override
    public boolean hasIno() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 ino = 2;</code>
     * @return The ino.
     */
    @java.lang.Override
    public long getIno() {
      return ino_;
    }
    /**
     * <code>optional uint64 ino = 2;</code>
     * @param value The ino to set.
     * @return This builder for chaining.
     */
    public Builder setIno(long value) {
      
      ino_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 ino = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIno() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ino_ = 0L;
      onChanged();
      return this;
    }

    private long block_ ;
    /**
     * <code>optional uint64 block = 3;</code>
     * @return Whether the block field is set.
     */
    @java.lang.Override
    public boolean hasBlock() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 block = 3;</code>
     * @return The block.
     */
    @java.lang.Override
    public long getBlock() {
      return block_;
    }
    /**
     * <code>optional uint64 block = 3;</code>
     * @param value The block to set.
     * @return This builder for chaining.
     */
    public Builder setBlock(long value) {
      
      block_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 block = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlock() {
      bitField0_ = (bitField0_ & ~0x00000004);
      block_ = 0L;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>optional uint32 count = 4;</code>
     * @return Whether the count field is set.
     */
    @java.lang.Override
    public boolean hasCount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 count = 4;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>optional uint32 count = 4;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      count_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.Ext4MbReleaseInodePaFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.Ext4MbReleaseInodePaFtraceEvent)
  private static final perfetto.protos.Ext4MbReleaseInodePaFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.Ext4MbReleaseInodePaFtraceEvent();
  }

  public static perfetto.protos.Ext4MbReleaseInodePaFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Ext4MbReleaseInodePaFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<Ext4MbReleaseInodePaFtraceEvent>() {
    @java.lang.Override
    public Ext4MbReleaseInodePaFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ext4MbReleaseInodePaFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ext4MbReleaseInodePaFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.Ext4MbReleaseInodePaFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

