// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.Ext4MballocPreallocFtraceEvent}
 */
public final class Ext4MballocPreallocFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.Ext4MballocPreallocFtraceEvent)
    Ext4MballocPreallocFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ext4MballocPreallocFtraceEvent.newBuilder() to construct.
  private Ext4MballocPreallocFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ext4MballocPreallocFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ext4MballocPreallocFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MballocPreallocFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MballocPreallocFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.Ext4MballocPreallocFtraceEvent.class, perfetto.protos.Ext4MballocPreallocFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int DEV_FIELD_NUMBER = 1;
  private long dev_ = 0L;
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return Whether the dev field is set.
   */
  @java.lang.Override
  public boolean hasDev() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return The dev.
   */
  @java.lang.Override
  public long getDev() {
    return dev_;
  }

  public static final int INO_FIELD_NUMBER = 2;
  private long ino_ = 0L;
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return Whether the ino field is set.
   */
  @java.lang.Override
  public boolean hasIno() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return The ino.
   */
  @java.lang.Override
  public long getIno() {
    return ino_;
  }

  public static final int ORIG_LOGICAL_FIELD_NUMBER = 3;
  private int origLogical_ = 0;
  /**
   * <code>optional uint32 orig_logical = 3;</code>
   * @return Whether the origLogical field is set.
   */
  @java.lang.Override
  public boolean hasOrigLogical() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 orig_logical = 3;</code>
   * @return The origLogical.
   */
  @java.lang.Override
  public int getOrigLogical() {
    return origLogical_;
  }

  public static final int ORIG_START_FIELD_NUMBER = 4;
  private int origStart_ = 0;
  /**
   * <code>optional int32 orig_start = 4;</code>
   * @return Whether the origStart field is set.
   */
  @java.lang.Override
  public boolean hasOrigStart() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 orig_start = 4;</code>
   * @return The origStart.
   */
  @java.lang.Override
  public int getOrigStart() {
    return origStart_;
  }

  public static final int ORIG_GROUP_FIELD_NUMBER = 5;
  private int origGroup_ = 0;
  /**
   * <code>optional uint32 orig_group = 5;</code>
   * @return Whether the origGroup field is set.
   */
  @java.lang.Override
  public boolean hasOrigGroup() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional uint32 orig_group = 5;</code>
   * @return The origGroup.
   */
  @java.lang.Override
  public int getOrigGroup() {
    return origGroup_;
  }

  public static final int ORIG_LEN_FIELD_NUMBER = 6;
  private int origLen_ = 0;
  /**
   * <code>optional int32 orig_len = 6;</code>
   * @return Whether the origLen field is set.
   */
  @java.lang.Override
  public boolean hasOrigLen() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 orig_len = 6;</code>
   * @return The origLen.
   */
  @java.lang.Override
  public int getOrigLen() {
    return origLen_;
  }

  public static final int RESULT_LOGICAL_FIELD_NUMBER = 7;
  private int resultLogical_ = 0;
  /**
   * <code>optional uint32 result_logical = 7;</code>
   * @return Whether the resultLogical field is set.
   */
  @java.lang.Override
  public boolean hasResultLogical() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint32 result_logical = 7;</code>
   * @return The resultLogical.
   */
  @java.lang.Override
  public int getResultLogical() {
    return resultLogical_;
  }

  public static final int RESULT_START_FIELD_NUMBER = 8;
  private int resultStart_ = 0;
  /**
   * <code>optional int32 result_start = 8;</code>
   * @return Whether the resultStart field is set.
   */
  @java.lang.Override
  public boolean hasResultStart() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int32 result_start = 8;</code>
   * @return The resultStart.
   */
  @java.lang.Override
  public int getResultStart() {
    return resultStart_;
  }

  public static final int RESULT_GROUP_FIELD_NUMBER = 9;
  private int resultGroup_ = 0;
  /**
   * <code>optional uint32 result_group = 9;</code>
   * @return Whether the resultGroup field is set.
   */
  @java.lang.Override
  public boolean hasResultGroup() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional uint32 result_group = 9;</code>
   * @return The resultGroup.
   */
  @java.lang.Override
  public int getResultGroup() {
    return resultGroup_;
  }

  public static final int RESULT_LEN_FIELD_NUMBER = 10;
  private int resultLen_ = 0;
  /**
   * <code>optional int32 result_len = 10;</code>
   * @return Whether the resultLen field is set.
   */
  @java.lang.Override
  public boolean hasResultLen() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional int32 result_len = 10;</code>
   * @return The resultLen.
   */
  @java.lang.Override
  public int getResultLen() {
    return resultLen_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, dev_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt64(2, ino_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, origLogical_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, origStart_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeUInt32(5, origGroup_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, origLen_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt32(7, resultLogical_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, resultStart_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeUInt32(9, resultGroup_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeInt32(10, resultLen_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, dev_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, ino_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, origLogical_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, origStart_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, origGroup_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, origLen_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, resultLogical_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, resultStart_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, resultGroup_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, resultLen_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.Ext4MballocPreallocFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.Ext4MballocPreallocFtraceEvent other = (perfetto.protos.Ext4MballocPreallocFtraceEvent) obj;

    if (hasDev() != other.hasDev()) return false;
    if (hasDev()) {
      if (getDev()
          != other.getDev()) return false;
    }
    if (hasIno() != other.hasIno()) return false;
    if (hasIno()) {
      if (getIno()
          != other.getIno()) return false;
    }
    if (hasOrigLogical() != other.hasOrigLogical()) return false;
    if (hasOrigLogical()) {
      if (getOrigLogical()
          != other.getOrigLogical()) return false;
    }
    if (hasOrigStart() != other.hasOrigStart()) return false;
    if (hasOrigStart()) {
      if (getOrigStart()
          != other.getOrigStart()) return false;
    }
    if (hasOrigGroup() != other.hasOrigGroup()) return false;
    if (hasOrigGroup()) {
      if (getOrigGroup()
          != other.getOrigGroup()) return false;
    }
    if (hasOrigLen() != other.hasOrigLen()) return false;
    if (hasOrigLen()) {
      if (getOrigLen()
          != other.getOrigLen()) return false;
    }
    if (hasResultLogical() != other.hasResultLogical()) return false;
    if (hasResultLogical()) {
      if (getResultLogical()
          != other.getResultLogical()) return false;
    }
    if (hasResultStart() != other.hasResultStart()) return false;
    if (hasResultStart()) {
      if (getResultStart()
          != other.getResultStart()) return false;
    }
    if (hasResultGroup() != other.hasResultGroup()) return false;
    if (hasResultGroup()) {
      if (getResultGroup()
          != other.getResultGroup()) return false;
    }
    if (hasResultLen() != other.hasResultLen()) return false;
    if (hasResultLen()) {
      if (getResultLen()
          != other.getResultLen()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDev()) {
      hash = (37 * hash) + DEV_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDev());
    }
    if (hasIno()) {
      hash = (37 * hash) + INO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIno());
    }
    if (hasOrigLogical()) {
      hash = (37 * hash) + ORIG_LOGICAL_FIELD_NUMBER;
      hash = (53 * hash) + getOrigLogical();
    }
    if (hasOrigStart()) {
      hash = (37 * hash) + ORIG_START_FIELD_NUMBER;
      hash = (53 * hash) + getOrigStart();
    }
    if (hasOrigGroup()) {
      hash = (37 * hash) + ORIG_GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getOrigGroup();
    }
    if (hasOrigLen()) {
      hash = (37 * hash) + ORIG_LEN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigLen();
    }
    if (hasResultLogical()) {
      hash = (37 * hash) + RESULT_LOGICAL_FIELD_NUMBER;
      hash = (53 * hash) + getResultLogical();
    }
    if (hasResultStart()) {
      hash = (37 * hash) + RESULT_START_FIELD_NUMBER;
      hash = (53 * hash) + getResultStart();
    }
    if (hasResultGroup()) {
      hash = (37 * hash) + RESULT_GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getResultGroup();
    }
    if (hasResultLen()) {
      hash = (37 * hash) + RESULT_LEN_FIELD_NUMBER;
      hash = (53 * hash) + getResultLen();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.Ext4MballocPreallocFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.Ext4MballocPreallocFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.Ext4MballocPreallocFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.Ext4MballocPreallocFtraceEvent)
      perfetto.protos.Ext4MballocPreallocFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MballocPreallocFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MballocPreallocFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.Ext4MballocPreallocFtraceEvent.class, perfetto.protos.Ext4MballocPreallocFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.Ext4MballocPreallocFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dev_ = 0L;
      ino_ = 0L;
      origLogical_ = 0;
      origStart_ = 0;
      origGroup_ = 0;
      origLen_ = 0;
      resultLogical_ = 0;
      resultStart_ = 0;
      resultGroup_ = 0;
      resultLen_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Ext4MballocPreallocFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.Ext4MballocPreallocFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.Ext4MballocPreallocFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.Ext4MballocPreallocFtraceEvent build() {
      perfetto.protos.Ext4MballocPreallocFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.Ext4MballocPreallocFtraceEvent buildPartial() {
      perfetto.protos.Ext4MballocPreallocFtraceEvent result = new perfetto.protos.Ext4MballocPreallocFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.Ext4MballocPreallocFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dev_ = dev_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ino_ = ino_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.origLogical_ = origLogical_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.origStart_ = origStart_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.origGroup_ = origGroup_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.origLen_ = origLen_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.resultLogical_ = resultLogical_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.resultStart_ = resultStart_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.resultGroup_ = resultGroup_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.resultLen_ = resultLen_;
        to_bitField0_ |= 0x00000200;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.Ext4MballocPreallocFtraceEvent) {
        return mergeFrom((perfetto.protos.Ext4MballocPreallocFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.Ext4MballocPreallocFtraceEvent other) {
      if (other == perfetto.protos.Ext4MballocPreallocFtraceEvent.getDefaultInstance()) return this;
      if (other.hasDev()) {
        setDev(other.getDev());
      }
      if (other.hasIno()) {
        setIno(other.getIno());
      }
      if (other.hasOrigLogical()) {
        setOrigLogical(other.getOrigLogical());
      }
      if (other.hasOrigStart()) {
        setOrigStart(other.getOrigStart());
      }
      if (other.hasOrigGroup()) {
        setOrigGroup(other.getOrigGroup());
      }
      if (other.hasOrigLen()) {
        setOrigLen(other.getOrigLen());
      }
      if (other.hasResultLogical()) {
        setResultLogical(other.getResultLogical());
      }
      if (other.hasResultStart()) {
        setResultStart(other.getResultStart());
      }
      if (other.hasResultGroup()) {
        setResultGroup(other.getResultGroup());
      }
      if (other.hasResultLen()) {
        setResultLen(other.getResultLen());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              dev_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              ino_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              origLogical_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              origStart_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              origGroup_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              origLen_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              resultLogical_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              resultStart_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              resultGroup_ = input.readUInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              resultLen_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long dev_ ;
    /**
     * <code>optional uint64 dev = 1;</code>
     * @return Whether the dev field is set.
     */
    @java.lang.Override
    public boolean hasDev() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 dev = 1;</code>
     * @return The dev.
     */
    @java.lang.Override
    public long getDev() {
      return dev_;
    }
    /**
     * <code>optional uint64 dev = 1;</code>
     * @param value The dev to set.
     * @return This builder for chaining.
     */
    public Builder setDev(long value) {
      
      dev_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 dev = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDev() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dev_ = 0L;
      onChanged();
      return this;
    }

    private long ino_ ;
    /**
     * <code>optional uint64 ino = 2;</code>
     * @return Whether the ino field is set.
     */
    @java.lang.Override
    public boolean hasIno() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 ino = 2;</code>
     * @return The ino.
     */
    @java.lang.Override
    public long getIno() {
      return ino_;
    }
    /**
     * <code>optional uint64 ino = 2;</code>
     * @param value The ino to set.
     * @return This builder for chaining.
     */
    public Builder setIno(long value) {
      
      ino_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 ino = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIno() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ino_ = 0L;
      onChanged();
      return this;
    }

    private int origLogical_ ;
    /**
     * <code>optional uint32 orig_logical = 3;</code>
     * @return Whether the origLogical field is set.
     */
    @java.lang.Override
    public boolean hasOrigLogical() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 orig_logical = 3;</code>
     * @return The origLogical.
     */
    @java.lang.Override
    public int getOrigLogical() {
      return origLogical_;
    }
    /**
     * <code>optional uint32 orig_logical = 3;</code>
     * @param value The origLogical to set.
     * @return This builder for chaining.
     */
    public Builder setOrigLogical(int value) {
      
      origLogical_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 orig_logical = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigLogical() {
      bitField0_ = (bitField0_ & ~0x00000004);
      origLogical_ = 0;
      onChanged();
      return this;
    }

    private int origStart_ ;
    /**
     * <code>optional int32 orig_start = 4;</code>
     * @return Whether the origStart field is set.
     */
    @java.lang.Override
    public boolean hasOrigStart() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 orig_start = 4;</code>
     * @return The origStart.
     */
    @java.lang.Override
    public int getOrigStart() {
      return origStart_;
    }
    /**
     * <code>optional int32 orig_start = 4;</code>
     * @param value The origStart to set.
     * @return This builder for chaining.
     */
    public Builder setOrigStart(int value) {
      
      origStart_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 orig_start = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigStart() {
      bitField0_ = (bitField0_ & ~0x00000008);
      origStart_ = 0;
      onChanged();
      return this;
    }

    private int origGroup_ ;
    /**
     * <code>optional uint32 orig_group = 5;</code>
     * @return Whether the origGroup field is set.
     */
    @java.lang.Override
    public boolean hasOrigGroup() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 orig_group = 5;</code>
     * @return The origGroup.
     */
    @java.lang.Override
    public int getOrigGroup() {
      return origGroup_;
    }
    /**
     * <code>optional uint32 orig_group = 5;</code>
     * @param value The origGroup to set.
     * @return This builder for chaining.
     */
    public Builder setOrigGroup(int value) {
      
      origGroup_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 orig_group = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigGroup() {
      bitField0_ = (bitField0_ & ~0x00000010);
      origGroup_ = 0;
      onChanged();
      return this;
    }

    private int origLen_ ;
    /**
     * <code>optional int32 orig_len = 6;</code>
     * @return Whether the origLen field is set.
     */
    @java.lang.Override
    public boolean hasOrigLen() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 orig_len = 6;</code>
     * @return The origLen.
     */
    @java.lang.Override
    public int getOrigLen() {
      return origLen_;
    }
    /**
     * <code>optional int32 orig_len = 6;</code>
     * @param value The origLen to set.
     * @return This builder for chaining.
     */
    public Builder setOrigLen(int value) {
      
      origLen_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 orig_len = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigLen() {
      bitField0_ = (bitField0_ & ~0x00000020);
      origLen_ = 0;
      onChanged();
      return this;
    }

    private int resultLogical_ ;
    /**
     * <code>optional uint32 result_logical = 7;</code>
     * @return Whether the resultLogical field is set.
     */
    @java.lang.Override
    public boolean hasResultLogical() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 result_logical = 7;</code>
     * @return The resultLogical.
     */
    @java.lang.Override
    public int getResultLogical() {
      return resultLogical_;
    }
    /**
     * <code>optional uint32 result_logical = 7;</code>
     * @param value The resultLogical to set.
     * @return This builder for chaining.
     */
    public Builder setResultLogical(int value) {
      
      resultLogical_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 result_logical = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultLogical() {
      bitField0_ = (bitField0_ & ~0x00000040);
      resultLogical_ = 0;
      onChanged();
      return this;
    }

    private int resultStart_ ;
    /**
     * <code>optional int32 result_start = 8;</code>
     * @return Whether the resultStart field is set.
     */
    @java.lang.Override
    public boolean hasResultStart() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 result_start = 8;</code>
     * @return The resultStart.
     */
    @java.lang.Override
    public int getResultStart() {
      return resultStart_;
    }
    /**
     * <code>optional int32 result_start = 8;</code>
     * @param value The resultStart to set.
     * @return This builder for chaining.
     */
    public Builder setResultStart(int value) {
      
      resultStart_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 result_start = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultStart() {
      bitField0_ = (bitField0_ & ~0x00000080);
      resultStart_ = 0;
      onChanged();
      return this;
    }

    private int resultGroup_ ;
    /**
     * <code>optional uint32 result_group = 9;</code>
     * @return Whether the resultGroup field is set.
     */
    @java.lang.Override
    public boolean hasResultGroup() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint32 result_group = 9;</code>
     * @return The resultGroup.
     */
    @java.lang.Override
    public int getResultGroup() {
      return resultGroup_;
    }
    /**
     * <code>optional uint32 result_group = 9;</code>
     * @param value The resultGroup to set.
     * @return This builder for chaining.
     */
    public Builder setResultGroup(int value) {
      
      resultGroup_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 result_group = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultGroup() {
      bitField0_ = (bitField0_ & ~0x00000100);
      resultGroup_ = 0;
      onChanged();
      return this;
    }

    private int resultLen_ ;
    /**
     * <code>optional int32 result_len = 10;</code>
     * @return Whether the resultLen field is set.
     */
    @java.lang.Override
    public boolean hasResultLen() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int32 result_len = 10;</code>
     * @return The resultLen.
     */
    @java.lang.Override
    public int getResultLen() {
      return resultLen_;
    }
    /**
     * <code>optional int32 result_len = 10;</code>
     * @param value The resultLen to set.
     * @return This builder for chaining.
     */
    public Builder setResultLen(int value) {
      
      resultLen_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 result_len = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultLen() {
      bitField0_ = (bitField0_ & ~0x00000200);
      resultLen_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.Ext4MballocPreallocFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.Ext4MballocPreallocFtraceEvent)
  private static final perfetto.protos.Ext4MballocPreallocFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.Ext4MballocPreallocFtraceEvent();
  }

  public static perfetto.protos.Ext4MballocPreallocFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Ext4MballocPreallocFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<Ext4MballocPreallocFtraceEvent>() {
    @java.lang.Override
    public Ext4MballocPreallocFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ext4MballocPreallocFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ext4MballocPreallocFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.Ext4MballocPreallocFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

