// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface Ext4OtherInodeUpdateTimeFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.Ext4OtherInodeUpdateTimeFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 dev = 1;</code>
   * @return Whether the dev field is set.
   */
  boolean hasDev();
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return The dev.
   */
  long getDev();

  /**
   * <code>optional uint64 ino = 2;</code>
   * @return Whether the ino field is set.
   */
  boolean hasIno();
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return The ino.
   */
  long getIno();

  /**
   * <code>optional uint64 orig_ino = 3;</code>
   * @return Whether the origIno field is set.
   */
  boolean hasOrigIno();
  /**
   * <code>optional uint64 orig_ino = 3;</code>
   * @return The origIno.
   */
  long getOrigIno();

  /**
   * <code>optional uint32 uid = 4;</code>
   * @return Whether the uid field is set.
   */
  boolean hasUid();
  /**
   * <code>optional uint32 uid = 4;</code>
   * @return The uid.
   */
  int getUid();

  /**
   * <code>optional uint32 gid = 5;</code>
   * @return Whether the gid field is set.
   */
  boolean hasGid();
  /**
   * <code>optional uint32 gid = 5;</code>
   * @return The gid.
   */
  int getGid();

  /**
   * <code>optional uint32 mode = 6;</code>
   * @return Whether the mode field is set.
   */
  boolean hasMode();
  /**
   * <code>optional uint32 mode = 6;</code>
   * @return The mode.
   */
  int getMode();
}
