// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface Ext4ExtConvertToInitializedEnterFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.Ext4ExtConvertToInitializedEnterFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 dev = 1;</code>
   * @return Whether the dev field is set.
   */
  boolean hasDev();
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return The dev.
   */
  long getDev();

  /**
   * <code>optional uint64 ino = 2;</code>
   * @return Whether the ino field is set.
   */
  boolean hasIno();
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return The ino.
   */
  long getIno();

  /**
   * <code>optional uint32 m_lblk = 3;</code>
   * @return Whether the mLblk field is set.
   */
  boolean hasMLblk();
  /**
   * <code>optional uint32 m_lblk = 3;</code>
   * @return The mLblk.
   */
  int getMLblk();

  /**
   * <code>optional uint32 m_len = 4;</code>
   * @return Whether the mLen field is set.
   */
  boolean hasMLen();
  /**
   * <code>optional uint32 m_len = 4;</code>
   * @return The mLen.
   */
  int getMLen();

  /**
   * <code>optional uint32 u_lblk = 5;</code>
   * @return Whether the uLblk field is set.
   */
  boolean hasULblk();
  /**
   * <code>optional uint32 u_lblk = 5;</code>
   * @return The uLblk.
   */
  int getULblk();

  /**
   * <code>optional uint32 u_len = 6;</code>
   * @return Whether the uLen field is set.
   */
  boolean hasULen();
  /**
   * <code>optional uint32 u_len = 6;</code>
   * @return The uLen.
   */
  int getULen();

  /**
   * <code>optional uint64 u_pblk = 7;</code>
   * @return Whether the uPblk field is set.
   */
  boolean hasUPblk();
  /**
   * <code>optional uint64 u_pblk = 7;</code>
   * @return The uPblk.
   */
  long getUPblk();
}
