// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface Ext4ExtRemoveSpaceFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.Ext4ExtRemoveSpaceFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 dev = 1;</code>
   * @return Whether the dev field is set.
   */
  boolean hasDev();
  /**
   * <code>optional uint64 dev = 1;</code>
   * @return The dev.
   */
  long getDev();

  /**
   * <code>optional uint64 ino = 2;</code>
   * @return Whether the ino field is set.
   */
  boolean hasIno();
  /**
   * <code>optional uint64 ino = 2;</code>
   * @return The ino.
   */
  long getIno();

  /**
   * <code>optional uint32 start = 3;</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <code>optional uint32 start = 3;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <code>optional uint32 end = 4;</code>
   * @return Whether the end field is set.
   */
  boolean hasEnd();
  /**
   * <code>optional uint32 end = 4;</code>
   * @return The end.
   */
  int getEnd();

  /**
   * <code>optional int32 depth = 5;</code>
   * @return Whether the depth field is set.
   */
  boolean hasDepth();
  /**
   * <code>optional int32 depth = 5;</code>
   * @return The depth.
   */
  int getDepth();
}
