// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface GpuLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.GpuLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .perfetto.protos.GpuLog.Severity severity = 1;</code>
   * @return Whether the severity field is set.
   */
  boolean hasSeverity();
  /**
   * <code>optional .perfetto.protos.GpuLog.Severity severity = 1;</code>
   * @return The severity.
   */
  perfetto.protos.GpuLog.Severity getSeverity();

  /**
   * <code>optional string tag = 2;</code>
   * @return Whether the tag field is set.
   */
  boolean hasTag();
  /**
   * <code>optional string tag = 2;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 2;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>optional string log_message = 3;</code>
   * @return Whether the logMessage field is set.
   */
  boolean hasLogMessage();
  /**
   * <code>optional string log_message = 3;</code>
   * @return The logMessage.
   */
  java.lang.String getLogMessage();
  /**
   * <code>optional string log_message = 3;</code>
   * @return The bytes for logMessage.
   */
  com.google.protobuf.ByteString
      getLogMessageBytes();
}
