// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface IommuSecPtblMapRangeStartFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.IommuSecPtblMapRangeStartFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 len = 1;</code>
   * @return Whether the len field is set.
   */
  boolean hasLen();
  /**
   * <code>optional uint64 len = 1;</code>
   * @return The len.
   */
  long getLen();

  /**
   * <code>optional int32 num = 2;</code>
   * @return Whether the num field is set.
   */
  boolean hasNum();
  /**
   * <code>optional int32 num = 2;</code>
   * @return The num.
   */
  int getNum();

  /**
   * <code>optional uint32 pa = 3;</code>
   * @return Whether the pa field is set.
   */
  boolean hasPa();
  /**
   * <code>optional uint32 pa = 3;</code>
   * @return The pa.
   */
  int getPa();

  /**
   * <code>optional int32 sec_id = 4;</code>
   * @return Whether the secId field is set.
   */
  boolean hasSecId();
  /**
   * <code>optional int32 sec_id = 4;</code>
   * @return The secId.
   */
  int getSecId();

  /**
   * <code>optional uint64 va = 5;</code>
   * @return Whether the va field is set.
   */
  boolean hasVa();
  /**
   * <code>optional uint64 va = 5;</code>
   * @return The va.
   */
  long getVa();
}
