// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface IonSecureCmaAddToPoolEndFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.IonSecureCmaAddToPoolEndFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 is_prefetch = 1;</code>
   * @return Whether the isPrefetch field is set.
   */
  boolean hasIsPrefetch();
  /**
   * <code>optional uint32 is_prefetch = 1;</code>
   * @return The isPrefetch.
   */
  int getIsPrefetch();

  /**
   * <code>optional uint64 len = 2;</code>
   * @return Whether the len field is set.
   */
  boolean hasLen();
  /**
   * <code>optional uint64 len = 2;</code>
   * @return The len.
   */
  long getLen();

  /**
   * <code>optional int32 pool_total = 3;</code>
   * @return Whether the poolTotal field is set.
   */
  boolean hasPoolTotal();
  /**
   * <code>optional int32 pool_total = 3;</code>
   * @return The poolTotal.
   */
  int getPoolTotal();
}
