// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface KvmEntryFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.KvmEntryFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 vcpu_pc = 1;</code>
   * @return Whether the vcpuPc field is set.
   */
  boolean hasVcpuPc();
  /**
   * <code>optional uint64 vcpu_pc = 1;</code>
   * @return The vcpuPc.
   */
  long getVcpuPc();
}
