// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.MdpCommitFtraceEvent}
 */
public final class MdpCommitFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.MdpCommitFtraceEvent)
    MdpCommitFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MdpCommitFtraceEvent.newBuilder() to construct.
  private MdpCommitFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MdpCommitFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MdpCommitFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MdpCommitFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MdpCommitFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.MdpCommitFtraceEvent.class, perfetto.protos.MdpCommitFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int NUM_FIELD_NUMBER = 1;
  private int num_ = 0;
  /**
   * <code>optional uint32 num = 1;</code>
   * @return Whether the num field is set.
   */
  @java.lang.Override
  public boolean hasNum() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 num = 1;</code>
   * @return The num.
   */
  @java.lang.Override
  public int getNum() {
    return num_;
  }

  public static final int PLAY_CNT_FIELD_NUMBER = 2;
  private int playCnt_ = 0;
  /**
   * <code>optional uint32 play_cnt = 2;</code>
   * @return Whether the playCnt field is set.
   */
  @java.lang.Override
  public boolean hasPlayCnt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint32 play_cnt = 2;</code>
   * @return The playCnt.
   */
  @java.lang.Override
  public int getPlayCnt() {
    return playCnt_;
  }

  public static final int CLK_RATE_FIELD_NUMBER = 3;
  private int clkRate_ = 0;
  /**
   * <code>optional uint32 clk_rate = 3;</code>
   * @return Whether the clkRate field is set.
   */
  @java.lang.Override
  public boolean hasClkRate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 clk_rate = 3;</code>
   * @return The clkRate.
   */
  @java.lang.Override
  public int getClkRate() {
    return clkRate_;
  }

  public static final int BANDWIDTH_FIELD_NUMBER = 4;
  private long bandwidth_ = 0L;
  /**
   * <code>optional uint64 bandwidth = 4;</code>
   * @return Whether the bandwidth field is set.
   */
  @java.lang.Override
  public boolean hasBandwidth() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint64 bandwidth = 4;</code>
   * @return The bandwidth.
   */
  @java.lang.Override
  public long getBandwidth() {
    return bandwidth_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(1, num_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, playCnt_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, clkRate_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(4, bandwidth_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, num_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, playCnt_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, clkRate_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, bandwidth_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.MdpCommitFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.MdpCommitFtraceEvent other = (perfetto.protos.MdpCommitFtraceEvent) obj;

    if (hasNum() != other.hasNum()) return false;
    if (hasNum()) {
      if (getNum()
          != other.getNum()) return false;
    }
    if (hasPlayCnt() != other.hasPlayCnt()) return false;
    if (hasPlayCnt()) {
      if (getPlayCnt()
          != other.getPlayCnt()) return false;
    }
    if (hasClkRate() != other.hasClkRate()) return false;
    if (hasClkRate()) {
      if (getClkRate()
          != other.getClkRate()) return false;
    }
    if (hasBandwidth() != other.hasBandwidth()) return false;
    if (hasBandwidth()) {
      if (getBandwidth()
          != other.getBandwidth()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNum()) {
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
    }
    if (hasPlayCnt()) {
      hash = (37 * hash) + PLAY_CNT_FIELD_NUMBER;
      hash = (53 * hash) + getPlayCnt();
    }
    if (hasClkRate()) {
      hash = (37 * hash) + CLK_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getClkRate();
    }
    if (hasBandwidth()) {
      hash = (37 * hash) + BANDWIDTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBandwidth());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.MdpCommitFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.MdpCommitFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.MdpCommitFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.MdpCommitFtraceEvent)
      perfetto.protos.MdpCommitFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MdpCommitFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MdpCommitFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.MdpCommitFtraceEvent.class, perfetto.protos.MdpCommitFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.MdpCommitFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      num_ = 0;
      playCnt_ = 0;
      clkRate_ = 0;
      bandwidth_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MdpCommitFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.MdpCommitFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.MdpCommitFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.MdpCommitFtraceEvent build() {
      perfetto.protos.MdpCommitFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.MdpCommitFtraceEvent buildPartial() {
      perfetto.protos.MdpCommitFtraceEvent result = new perfetto.protos.MdpCommitFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.MdpCommitFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.num_ = num_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.playCnt_ = playCnt_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.clkRate_ = clkRate_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bandwidth_ = bandwidth_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.MdpCommitFtraceEvent) {
        return mergeFrom((perfetto.protos.MdpCommitFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.MdpCommitFtraceEvent other) {
      if (other == perfetto.protos.MdpCommitFtraceEvent.getDefaultInstance()) return this;
      if (other.hasNum()) {
        setNum(other.getNum());
      }
      if (other.hasPlayCnt()) {
        setPlayCnt(other.getPlayCnt());
      }
      if (other.hasClkRate()) {
        setClkRate(other.getClkRate());
      }
      if (other.hasBandwidth()) {
        setBandwidth(other.getBandwidth());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              num_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              playCnt_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              clkRate_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              bandwidth_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int num_ ;
    /**
     * <code>optional uint32 num = 1;</code>
     * @return Whether the num field is set.
     */
    @java.lang.Override
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 num = 1;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }
    /**
     * <code>optional uint32 num = 1;</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(int value) {
      
      num_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 num = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      num_ = 0;
      onChanged();
      return this;
    }

    private int playCnt_ ;
    /**
     * <code>optional uint32 play_cnt = 2;</code>
     * @return Whether the playCnt field is set.
     */
    @java.lang.Override
    public boolean hasPlayCnt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 play_cnt = 2;</code>
     * @return The playCnt.
     */
    @java.lang.Override
    public int getPlayCnt() {
      return playCnt_;
    }
    /**
     * <code>optional uint32 play_cnt = 2;</code>
     * @param value The playCnt to set.
     * @return This builder for chaining.
     */
    public Builder setPlayCnt(int value) {
      
      playCnt_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 play_cnt = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayCnt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      playCnt_ = 0;
      onChanged();
      return this;
    }

    private int clkRate_ ;
    /**
     * <code>optional uint32 clk_rate = 3;</code>
     * @return Whether the clkRate field is set.
     */
    @java.lang.Override
    public boolean hasClkRate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 clk_rate = 3;</code>
     * @return The clkRate.
     */
    @java.lang.Override
    public int getClkRate() {
      return clkRate_;
    }
    /**
     * <code>optional uint32 clk_rate = 3;</code>
     * @param value The clkRate to set.
     * @return This builder for chaining.
     */
    public Builder setClkRate(int value) {
      
      clkRate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 clk_rate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClkRate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      clkRate_ = 0;
      onChanged();
      return this;
    }

    private long bandwidth_ ;
    /**
     * <code>optional uint64 bandwidth = 4;</code>
     * @return Whether the bandwidth field is set.
     */
    @java.lang.Override
    public boolean hasBandwidth() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 bandwidth = 4;</code>
     * @return The bandwidth.
     */
    @java.lang.Override
    public long getBandwidth() {
      return bandwidth_;
    }
    /**
     * <code>optional uint64 bandwidth = 4;</code>
     * @param value The bandwidth to set.
     * @return This builder for chaining.
     */
    public Builder setBandwidth(long value) {
      
      bandwidth_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 bandwidth = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBandwidth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      bandwidth_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.MdpCommitFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.MdpCommitFtraceEvent)
  private static final perfetto.protos.MdpCommitFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.MdpCommitFtraceEvent();
  }

  public static perfetto.protos.MdpCommitFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MdpCommitFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<MdpCommitFtraceEvent>() {
    @java.lang.Override
    public MdpCommitFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MdpCommitFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MdpCommitFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.MdpCommitFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

