// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface MdpTraceCounterFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.MdpTraceCounterFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 pid = 1;</code>
   * @return Whether the pid field is set.
   */
  boolean hasPid();
  /**
   * <code>optional int32 pid = 1;</code>
   * @return The pid.
   */
  int getPid();

  /**
   * <code>optional string counter_name = 2;</code>
   * @return Whether the counterName field is set.
   */
  boolean hasCounterName();
  /**
   * <code>optional string counter_name = 2;</code>
   * @return The counterName.
   */
  java.lang.String getCounterName();
  /**
   * <code>optional string counter_name = 2;</code>
   * @return The bytes for counterName.
   */
  com.google.protobuf.ByteString
      getCounterNameBytes();

  /**
   * <code>optional int32 value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional int32 value = 3;</code>
   * @return The value.
   */
  int getValue();
}
