// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.MmPageAllocZoneLockedFtraceEvent}
 */
public final class MmPageAllocZoneLockedFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.MmPageAllocZoneLockedFtraceEvent)
    MmPageAllocZoneLockedFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MmPageAllocZoneLockedFtraceEvent.newBuilder() to construct.
  private MmPageAllocZoneLockedFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MmPageAllocZoneLockedFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MmPageAllocZoneLockedFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmPageAllocZoneLockedFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmPageAllocZoneLockedFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.MmPageAllocZoneLockedFtraceEvent.class, perfetto.protos.MmPageAllocZoneLockedFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int MIGRATETYPE_FIELD_NUMBER = 1;
  private int migratetype_ = 0;
  /**
   * <code>optional int32 migratetype = 1;</code>
   * @return Whether the migratetype field is set.
   */
  @java.lang.Override
  public boolean hasMigratetype() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 migratetype = 1;</code>
   * @return The migratetype.
   */
  @java.lang.Override
  public int getMigratetype() {
    return migratetype_;
  }

  public static final int ORDER_FIELD_NUMBER = 2;
  private int order_ = 0;
  /**
   * <code>optional uint32 order = 2;</code>
   * @return Whether the order field is set.
   */
  @java.lang.Override
  public boolean hasOrder() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint32 order = 2;</code>
   * @return The order.
   */
  @java.lang.Override
  public int getOrder() {
    return order_;
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  private long page_ = 0L;
  /**
   * <code>optional uint64 page = 3;</code>
   * @return Whether the page field is set.
   */
  @java.lang.Override
  public boolean hasPage() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint64 page = 3;</code>
   * @return The page.
   */
  @java.lang.Override
  public long getPage() {
    return page_;
  }

  public static final int PFN_FIELD_NUMBER = 4;
  private long pfn_ = 0L;
  /**
   * <code>optional uint64 pfn = 4;</code>
   * @return Whether the pfn field is set.
   */
  @java.lang.Override
  public boolean hasPfn() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint64 pfn = 4;</code>
   * @return The pfn.
   */
  @java.lang.Override
  public long getPfn() {
    return pfn_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, migratetype_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, order_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt64(3, page_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(4, pfn_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, migratetype_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, order_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, page_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, pfn_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.MmPageAllocZoneLockedFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.MmPageAllocZoneLockedFtraceEvent other = (perfetto.protos.MmPageAllocZoneLockedFtraceEvent) obj;

    if (hasMigratetype() != other.hasMigratetype()) return false;
    if (hasMigratetype()) {
      if (getMigratetype()
          != other.getMigratetype()) return false;
    }
    if (hasOrder() != other.hasOrder()) return false;
    if (hasOrder()) {
      if (getOrder()
          != other.getOrder()) return false;
    }
    if (hasPage() != other.hasPage()) return false;
    if (hasPage()) {
      if (getPage()
          != other.getPage()) return false;
    }
    if (hasPfn() != other.hasPfn()) return false;
    if (hasPfn()) {
      if (getPfn()
          != other.getPfn()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMigratetype()) {
      hash = (37 * hash) + MIGRATETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMigratetype();
    }
    if (hasOrder()) {
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getOrder();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPage());
    }
    if (hasPfn()) {
      hash = (37 * hash) + PFN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPfn());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.MmPageAllocZoneLockedFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.MmPageAllocZoneLockedFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.MmPageAllocZoneLockedFtraceEvent)
      perfetto.protos.MmPageAllocZoneLockedFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmPageAllocZoneLockedFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmPageAllocZoneLockedFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.MmPageAllocZoneLockedFtraceEvent.class, perfetto.protos.MmPageAllocZoneLockedFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.MmPageAllocZoneLockedFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      migratetype_ = 0;
      order_ = 0;
      page_ = 0L;
      pfn_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmPageAllocZoneLockedFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.MmPageAllocZoneLockedFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.MmPageAllocZoneLockedFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.MmPageAllocZoneLockedFtraceEvent build() {
      perfetto.protos.MmPageAllocZoneLockedFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.MmPageAllocZoneLockedFtraceEvent buildPartial() {
      perfetto.protos.MmPageAllocZoneLockedFtraceEvent result = new perfetto.protos.MmPageAllocZoneLockedFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.MmPageAllocZoneLockedFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.migratetype_ = migratetype_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.order_ = order_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = page_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pfn_ = pfn_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.MmPageAllocZoneLockedFtraceEvent) {
        return mergeFrom((perfetto.protos.MmPageAllocZoneLockedFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.MmPageAllocZoneLockedFtraceEvent other) {
      if (other == perfetto.protos.MmPageAllocZoneLockedFtraceEvent.getDefaultInstance()) return this;
      if (other.hasMigratetype()) {
        setMigratetype(other.getMigratetype());
      }
      if (other.hasOrder()) {
        setOrder(other.getOrder());
      }
      if (other.hasPage()) {
        setPage(other.getPage());
      }
      if (other.hasPfn()) {
        setPfn(other.getPfn());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              migratetype_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              order_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              page_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              pfn_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int migratetype_ ;
    /**
     * <code>optional int32 migratetype = 1;</code>
     * @return Whether the migratetype field is set.
     */
    @java.lang.Override
    public boolean hasMigratetype() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 migratetype = 1;</code>
     * @return The migratetype.
     */
    @java.lang.Override
    public int getMigratetype() {
      return migratetype_;
    }
    /**
     * <code>optional int32 migratetype = 1;</code>
     * @param value The migratetype to set.
     * @return This builder for chaining.
     */
    public Builder setMigratetype(int value) {
      
      migratetype_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 migratetype = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMigratetype() {
      bitField0_ = (bitField0_ & ~0x00000001);
      migratetype_ = 0;
      onChanged();
      return this;
    }

    private int order_ ;
    /**
     * <code>optional uint32 order = 2;</code>
     * @return Whether the order field is set.
     */
    @java.lang.Override
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 order = 2;</code>
     * @return The order.
     */
    @java.lang.Override
    public int getOrder() {
      return order_;
    }
    /**
     * <code>optional uint32 order = 2;</code>
     * @param value The order to set.
     * @return This builder for chaining.
     */
    public Builder setOrder(int value) {
      
      order_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 order = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrder() {
      bitField0_ = (bitField0_ & ~0x00000002);
      order_ = 0;
      onChanged();
      return this;
    }

    private long page_ ;
    /**
     * <code>optional uint64 page = 3;</code>
     * @return Whether the page field is set.
     */
    @java.lang.Override
    public boolean hasPage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 page = 3;</code>
     * @return The page.
     */
    @java.lang.Override
    public long getPage() {
      return page_;
    }
    /**
     * <code>optional uint64 page = 3;</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(long value) {
      
      page_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 page = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = 0L;
      onChanged();
      return this;
    }

    private long pfn_ ;
    /**
     * <code>optional uint64 pfn = 4;</code>
     * @return Whether the pfn field is set.
     */
    @java.lang.Override
    public boolean hasPfn() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 pfn = 4;</code>
     * @return The pfn.
     */
    @java.lang.Override
    public long getPfn() {
      return pfn_;
    }
    /**
     * <code>optional uint64 pfn = 4;</code>
     * @param value The pfn to set.
     * @return This builder for chaining.
     */
    public Builder setPfn(long value) {
      
      pfn_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 pfn = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPfn() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pfn_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.MmPageAllocZoneLockedFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.MmPageAllocZoneLockedFtraceEvent)
  private static final perfetto.protos.MmPageAllocZoneLockedFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.MmPageAllocZoneLockedFtraceEvent();
  }

  public static perfetto.protos.MmPageAllocZoneLockedFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MmPageAllocZoneLockedFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<MmPageAllocZoneLockedFtraceEvent>() {
    @java.lang.Override
    public MmPageAllocZoneLockedFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MmPageAllocZoneLockedFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MmPageAllocZoneLockedFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.MmPageAllocZoneLockedFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

