// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.MmShrinkSlabStartFtraceEvent}
 */
public final class MmShrinkSlabStartFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.MmShrinkSlabStartFtraceEvent)
    MmShrinkSlabStartFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MmShrinkSlabStartFtraceEvent.newBuilder() to construct.
  private MmShrinkSlabStartFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MmShrinkSlabStartFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MmShrinkSlabStartFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmShrinkSlabStartFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmShrinkSlabStartFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.MmShrinkSlabStartFtraceEvent.class, perfetto.protos.MmShrinkSlabStartFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int CACHE_ITEMS_FIELD_NUMBER = 1;
  private long cacheItems_ = 0L;
  /**
   * <code>optional uint64 cache_items = 1;</code>
   * @return Whether the cacheItems field is set.
   */
  @java.lang.Override
  public boolean hasCacheItems() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 cache_items = 1;</code>
   * @return The cacheItems.
   */
  @java.lang.Override
  public long getCacheItems() {
    return cacheItems_;
  }

  public static final int DELTA_FIELD_NUMBER = 2;
  private long delta_ = 0L;
  /**
   * <code>optional uint64 delta = 2;</code>
   * @return Whether the delta field is set.
   */
  @java.lang.Override
  public boolean hasDelta() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint64 delta = 2;</code>
   * @return The delta.
   */
  @java.lang.Override
  public long getDelta() {
    return delta_;
  }

  public static final int GFP_FLAGS_FIELD_NUMBER = 3;
  private int gfpFlags_ = 0;
  /**
   * <code>optional uint32 gfp_flags = 3;</code>
   * @return Whether the gfpFlags field is set.
   */
  @java.lang.Override
  public boolean hasGfpFlags() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 gfp_flags = 3;</code>
   * @return The gfpFlags.
   */
  @java.lang.Override
  public int getGfpFlags() {
    return gfpFlags_;
  }

  public static final int LRU_PGS_FIELD_NUMBER = 4;
  private long lruPgs_ = 0L;
  /**
   * <code>optional uint64 lru_pgs = 4;</code>
   * @return Whether the lruPgs field is set.
   */
  @java.lang.Override
  public boolean hasLruPgs() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint64 lru_pgs = 4;</code>
   * @return The lruPgs.
   */
  @java.lang.Override
  public long getLruPgs() {
    return lruPgs_;
  }

  public static final int NR_OBJECTS_TO_SHRINK_FIELD_NUMBER = 5;
  private long nrObjectsToShrink_ = 0L;
  /**
   * <code>optional int64 nr_objects_to_shrink = 5;</code>
   * @return Whether the nrObjectsToShrink field is set.
   */
  @java.lang.Override
  public boolean hasNrObjectsToShrink() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int64 nr_objects_to_shrink = 5;</code>
   * @return The nrObjectsToShrink.
   */
  @java.lang.Override
  public long getNrObjectsToShrink() {
    return nrObjectsToShrink_;
  }

  public static final int PGS_SCANNED_FIELD_NUMBER = 6;
  private long pgsScanned_ = 0L;
  /**
   * <code>optional uint64 pgs_scanned = 6;</code>
   * @return Whether the pgsScanned field is set.
   */
  @java.lang.Override
  public boolean hasPgsScanned() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional uint64 pgs_scanned = 6;</code>
   * @return The pgsScanned.
   */
  @java.lang.Override
  public long getPgsScanned() {
    return pgsScanned_;
  }

  public static final int SHR_FIELD_NUMBER = 7;
  private long shr_ = 0L;
  /**
   * <code>optional uint64 shr = 7;</code>
   * @return Whether the shr field is set.
   */
  @java.lang.Override
  public boolean hasShr() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint64 shr = 7;</code>
   * @return The shr.
   */
  @java.lang.Override
  public long getShr() {
    return shr_;
  }

  public static final int SHRINK_FIELD_NUMBER = 8;
  private long shrink_ = 0L;
  /**
   * <code>optional uint64 shrink = 8;</code>
   * @return Whether the shrink field is set.
   */
  @java.lang.Override
  public boolean hasShrink() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional uint64 shrink = 8;</code>
   * @return The shrink.
   */
  @java.lang.Override
  public long getShrink() {
    return shrink_;
  }

  public static final int TOTAL_SCAN_FIELD_NUMBER = 9;
  private long totalScan_ = 0L;
  /**
   * <code>optional uint64 total_scan = 9;</code>
   * @return Whether the totalScan field is set.
   */
  @java.lang.Override
  public boolean hasTotalScan() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional uint64 total_scan = 9;</code>
   * @return The totalScan.
   */
  @java.lang.Override
  public long getTotalScan() {
    return totalScan_;
  }

  public static final int NID_FIELD_NUMBER = 10;
  private int nid_ = 0;
  /**
   * <code>optional int32 nid = 10;</code>
   * @return Whether the nid field is set.
   */
  @java.lang.Override
  public boolean hasNid() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional int32 nid = 10;</code>
   * @return The nid.
   */
  @java.lang.Override
  public int getNid() {
    return nid_;
  }

  public static final int PRIORITY_FIELD_NUMBER = 11;
  private int priority_ = 0;
  /**
   * <code>optional int32 priority = 11;</code>
   * @return Whether the priority field is set.
   */
  @java.lang.Override
  public boolean hasPriority() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional int32 priority = 11;</code>
   * @return The priority.
   */
  @java.lang.Override
  public int getPriority() {
    return priority_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, cacheItems_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt64(2, delta_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, gfpFlags_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(4, lruPgs_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(5, nrObjectsToShrink_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeUInt64(6, pgsScanned_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt64(7, shr_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeUInt64(8, shrink_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeUInt64(9, totalScan_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeInt32(10, nid_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      output.writeInt32(11, priority_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, cacheItems_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, delta_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, gfpFlags_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, lruPgs_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, nrObjectsToShrink_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, pgsScanned_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, shr_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, shrink_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, totalScan_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, nid_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, priority_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.MmShrinkSlabStartFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.MmShrinkSlabStartFtraceEvent other = (perfetto.protos.MmShrinkSlabStartFtraceEvent) obj;

    if (hasCacheItems() != other.hasCacheItems()) return false;
    if (hasCacheItems()) {
      if (getCacheItems()
          != other.getCacheItems()) return false;
    }
    if (hasDelta() != other.hasDelta()) return false;
    if (hasDelta()) {
      if (getDelta()
          != other.getDelta()) return false;
    }
    if (hasGfpFlags() != other.hasGfpFlags()) return false;
    if (hasGfpFlags()) {
      if (getGfpFlags()
          != other.getGfpFlags()) return false;
    }
    if (hasLruPgs() != other.hasLruPgs()) return false;
    if (hasLruPgs()) {
      if (getLruPgs()
          != other.getLruPgs()) return false;
    }
    if (hasNrObjectsToShrink() != other.hasNrObjectsToShrink()) return false;
    if (hasNrObjectsToShrink()) {
      if (getNrObjectsToShrink()
          != other.getNrObjectsToShrink()) return false;
    }
    if (hasPgsScanned() != other.hasPgsScanned()) return false;
    if (hasPgsScanned()) {
      if (getPgsScanned()
          != other.getPgsScanned()) return false;
    }
    if (hasShr() != other.hasShr()) return false;
    if (hasShr()) {
      if (getShr()
          != other.getShr()) return false;
    }
    if (hasShrink() != other.hasShrink()) return false;
    if (hasShrink()) {
      if (getShrink()
          != other.getShrink()) return false;
    }
    if (hasTotalScan() != other.hasTotalScan()) return false;
    if (hasTotalScan()) {
      if (getTotalScan()
          != other.getTotalScan()) return false;
    }
    if (hasNid() != other.hasNid()) return false;
    if (hasNid()) {
      if (getNid()
          != other.getNid()) return false;
    }
    if (hasPriority() != other.hasPriority()) return false;
    if (hasPriority()) {
      if (getPriority()
          != other.getPriority()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCacheItems()) {
      hash = (37 * hash) + CACHE_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCacheItems());
    }
    if (hasDelta()) {
      hash = (37 * hash) + DELTA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDelta());
    }
    if (hasGfpFlags()) {
      hash = (37 * hash) + GFP_FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getGfpFlags();
    }
    if (hasLruPgs()) {
      hash = (37 * hash) + LRU_PGS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLruPgs());
    }
    if (hasNrObjectsToShrink()) {
      hash = (37 * hash) + NR_OBJECTS_TO_SHRINK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNrObjectsToShrink());
    }
    if (hasPgsScanned()) {
      hash = (37 * hash) + PGS_SCANNED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPgsScanned());
    }
    if (hasShr()) {
      hash = (37 * hash) + SHR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShr());
    }
    if (hasShrink()) {
      hash = (37 * hash) + SHRINK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShrink());
    }
    if (hasTotalScan()) {
      hash = (37 * hash) + TOTAL_SCAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalScan());
    }
    if (hasNid()) {
      hash = (37 * hash) + NID_FIELD_NUMBER;
      hash = (53 * hash) + getNid();
    }
    if (hasPriority()) {
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.MmShrinkSlabStartFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.MmShrinkSlabStartFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.MmShrinkSlabStartFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.MmShrinkSlabStartFtraceEvent)
      perfetto.protos.MmShrinkSlabStartFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmShrinkSlabStartFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmShrinkSlabStartFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.MmShrinkSlabStartFtraceEvent.class, perfetto.protos.MmShrinkSlabStartFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.MmShrinkSlabStartFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cacheItems_ = 0L;
      delta_ = 0L;
      gfpFlags_ = 0;
      lruPgs_ = 0L;
      nrObjectsToShrink_ = 0L;
      pgsScanned_ = 0L;
      shr_ = 0L;
      shrink_ = 0L;
      totalScan_ = 0L;
      nid_ = 0;
      priority_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_MmShrinkSlabStartFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.MmShrinkSlabStartFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.MmShrinkSlabStartFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.MmShrinkSlabStartFtraceEvent build() {
      perfetto.protos.MmShrinkSlabStartFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.MmShrinkSlabStartFtraceEvent buildPartial() {
      perfetto.protos.MmShrinkSlabStartFtraceEvent result = new perfetto.protos.MmShrinkSlabStartFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.MmShrinkSlabStartFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cacheItems_ = cacheItems_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.delta_ = delta_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gfpFlags_ = gfpFlags_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lruPgs_ = lruPgs_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.nrObjectsToShrink_ = nrObjectsToShrink_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.pgsScanned_ = pgsScanned_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.shr_ = shr_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.shrink_ = shrink_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.totalScan_ = totalScan_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.nid_ = nid_;
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.priority_ = priority_;
        to_bitField0_ |= 0x00000400;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.MmShrinkSlabStartFtraceEvent) {
        return mergeFrom((perfetto.protos.MmShrinkSlabStartFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.MmShrinkSlabStartFtraceEvent other) {
      if (other == perfetto.protos.MmShrinkSlabStartFtraceEvent.getDefaultInstance()) return this;
      if (other.hasCacheItems()) {
        setCacheItems(other.getCacheItems());
      }
      if (other.hasDelta()) {
        setDelta(other.getDelta());
      }
      if (other.hasGfpFlags()) {
        setGfpFlags(other.getGfpFlags());
      }
      if (other.hasLruPgs()) {
        setLruPgs(other.getLruPgs());
      }
      if (other.hasNrObjectsToShrink()) {
        setNrObjectsToShrink(other.getNrObjectsToShrink());
      }
      if (other.hasPgsScanned()) {
        setPgsScanned(other.getPgsScanned());
      }
      if (other.hasShr()) {
        setShr(other.getShr());
      }
      if (other.hasShrink()) {
        setShrink(other.getShrink());
      }
      if (other.hasTotalScan()) {
        setTotalScan(other.getTotalScan());
      }
      if (other.hasNid()) {
        setNid(other.getNid());
      }
      if (other.hasPriority()) {
        setPriority(other.getPriority());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              cacheItems_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              delta_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              gfpFlags_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lruPgs_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              nrObjectsToShrink_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              pgsScanned_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              shr_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              shrink_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              totalScan_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              nid_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              priority_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long cacheItems_ ;
    /**
     * <code>optional uint64 cache_items = 1;</code>
     * @return Whether the cacheItems field is set.
     */
    @java.lang.Override
    public boolean hasCacheItems() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 cache_items = 1;</code>
     * @return The cacheItems.
     */
    @java.lang.Override
    public long getCacheItems() {
      return cacheItems_;
    }
    /**
     * <code>optional uint64 cache_items = 1;</code>
     * @param value The cacheItems to set.
     * @return This builder for chaining.
     */
    public Builder setCacheItems(long value) {
      
      cacheItems_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 cache_items = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheItems() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cacheItems_ = 0L;
      onChanged();
      return this;
    }

    private long delta_ ;
    /**
     * <code>optional uint64 delta = 2;</code>
     * @return Whether the delta field is set.
     */
    @java.lang.Override
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 delta = 2;</code>
     * @return The delta.
     */
    @java.lang.Override
    public long getDelta() {
      return delta_;
    }
    /**
     * <code>optional uint64 delta = 2;</code>
     * @param value The delta to set.
     * @return This builder for chaining.
     */
    public Builder setDelta(long value) {
      
      delta_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 delta = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelta() {
      bitField0_ = (bitField0_ & ~0x00000002);
      delta_ = 0L;
      onChanged();
      return this;
    }

    private int gfpFlags_ ;
    /**
     * <code>optional uint32 gfp_flags = 3;</code>
     * @return Whether the gfpFlags field is set.
     */
    @java.lang.Override
    public boolean hasGfpFlags() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 gfp_flags = 3;</code>
     * @return The gfpFlags.
     */
    @java.lang.Override
    public int getGfpFlags() {
      return gfpFlags_;
    }
    /**
     * <code>optional uint32 gfp_flags = 3;</code>
     * @param value The gfpFlags to set.
     * @return This builder for chaining.
     */
    public Builder setGfpFlags(int value) {
      
      gfpFlags_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 gfp_flags = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGfpFlags() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gfpFlags_ = 0;
      onChanged();
      return this;
    }

    private long lruPgs_ ;
    /**
     * <code>optional uint64 lru_pgs = 4;</code>
     * @return Whether the lruPgs field is set.
     */
    @java.lang.Override
    public boolean hasLruPgs() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 lru_pgs = 4;</code>
     * @return The lruPgs.
     */
    @java.lang.Override
    public long getLruPgs() {
      return lruPgs_;
    }
    /**
     * <code>optional uint64 lru_pgs = 4;</code>
     * @param value The lruPgs to set.
     * @return This builder for chaining.
     */
    public Builder setLruPgs(long value) {
      
      lruPgs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 lru_pgs = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLruPgs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lruPgs_ = 0L;
      onChanged();
      return this;
    }

    private long nrObjectsToShrink_ ;
    /**
     * <code>optional int64 nr_objects_to_shrink = 5;</code>
     * @return Whether the nrObjectsToShrink field is set.
     */
    @java.lang.Override
    public boolean hasNrObjectsToShrink() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 nr_objects_to_shrink = 5;</code>
     * @return The nrObjectsToShrink.
     */
    @java.lang.Override
    public long getNrObjectsToShrink() {
      return nrObjectsToShrink_;
    }
    /**
     * <code>optional int64 nr_objects_to_shrink = 5;</code>
     * @param value The nrObjectsToShrink to set.
     * @return This builder for chaining.
     */
    public Builder setNrObjectsToShrink(long value) {
      
      nrObjectsToShrink_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 nr_objects_to_shrink = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNrObjectsToShrink() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nrObjectsToShrink_ = 0L;
      onChanged();
      return this;
    }

    private long pgsScanned_ ;
    /**
     * <code>optional uint64 pgs_scanned = 6;</code>
     * @return Whether the pgsScanned field is set.
     */
    @java.lang.Override
    public boolean hasPgsScanned() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint64 pgs_scanned = 6;</code>
     * @return The pgsScanned.
     */
    @java.lang.Override
    public long getPgsScanned() {
      return pgsScanned_;
    }
    /**
     * <code>optional uint64 pgs_scanned = 6;</code>
     * @param value The pgsScanned to set.
     * @return This builder for chaining.
     */
    public Builder setPgsScanned(long value) {
      
      pgsScanned_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 pgs_scanned = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPgsScanned() {
      bitField0_ = (bitField0_ & ~0x00000020);
      pgsScanned_ = 0L;
      onChanged();
      return this;
    }

    private long shr_ ;
    /**
     * <code>optional uint64 shr = 7;</code>
     * @return Whether the shr field is set.
     */
    @java.lang.Override
    public boolean hasShr() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint64 shr = 7;</code>
     * @return The shr.
     */
    @java.lang.Override
    public long getShr() {
      return shr_;
    }
    /**
     * <code>optional uint64 shr = 7;</code>
     * @param value The shr to set.
     * @return This builder for chaining.
     */
    public Builder setShr(long value) {
      
      shr_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 shr = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearShr() {
      bitField0_ = (bitField0_ & ~0x00000040);
      shr_ = 0L;
      onChanged();
      return this;
    }

    private long shrink_ ;
    /**
     * <code>optional uint64 shrink = 8;</code>
     * @return Whether the shrink field is set.
     */
    @java.lang.Override
    public boolean hasShrink() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint64 shrink = 8;</code>
     * @return The shrink.
     */
    @java.lang.Override
    public long getShrink() {
      return shrink_;
    }
    /**
     * <code>optional uint64 shrink = 8;</code>
     * @param value The shrink to set.
     * @return This builder for chaining.
     */
    public Builder setShrink(long value) {
      
      shrink_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 shrink = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearShrink() {
      bitField0_ = (bitField0_ & ~0x00000080);
      shrink_ = 0L;
      onChanged();
      return this;
    }

    private long totalScan_ ;
    /**
     * <code>optional uint64 total_scan = 9;</code>
     * @return Whether the totalScan field is set.
     */
    @java.lang.Override
    public boolean hasTotalScan() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint64 total_scan = 9;</code>
     * @return The totalScan.
     */
    @java.lang.Override
    public long getTotalScan() {
      return totalScan_;
    }
    /**
     * <code>optional uint64 total_scan = 9;</code>
     * @param value The totalScan to set.
     * @return This builder for chaining.
     */
    public Builder setTotalScan(long value) {
      
      totalScan_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 total_scan = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalScan() {
      bitField0_ = (bitField0_ & ~0x00000100);
      totalScan_ = 0L;
      onChanged();
      return this;
    }

    private int nid_ ;
    /**
     * <code>optional int32 nid = 10;</code>
     * @return Whether the nid field is set.
     */
    @java.lang.Override
    public boolean hasNid() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int32 nid = 10;</code>
     * @return The nid.
     */
    @java.lang.Override
    public int getNid() {
      return nid_;
    }
    /**
     * <code>optional int32 nid = 10;</code>
     * @param value The nid to set.
     * @return This builder for chaining.
     */
    public Builder setNid(int value) {
      
      nid_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 nid = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearNid() {
      bitField0_ = (bitField0_ & ~0x00000200);
      nid_ = 0;
      onChanged();
      return this;
    }

    private int priority_ ;
    /**
     * <code>optional int32 priority = 11;</code>
     * @return Whether the priority field is set.
     */
    @java.lang.Override
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional int32 priority = 11;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }
    /**
     * <code>optional int32 priority = 11;</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(int value) {
      
      priority_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 priority = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000400);
      priority_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.MmShrinkSlabStartFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.MmShrinkSlabStartFtraceEvent)
  private static final perfetto.protos.MmShrinkSlabStartFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.MmShrinkSlabStartFtraceEvent();
  }

  public static perfetto.protos.MmShrinkSlabStartFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MmShrinkSlabStartFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<MmShrinkSlabStartFtraceEvent>() {
    @java.lang.Override
    public MmShrinkSlabStartFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MmShrinkSlabStartFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MmShrinkSlabStartFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.MmShrinkSlabStartFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

