// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.PrintFtraceEvent}
 */
public final class PrintFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.PrintFtraceEvent)
    PrintFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PrintFtraceEvent.newBuilder() to construct.
  private PrintFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PrintFtraceEvent() {
    buf_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PrintFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_PrintFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_PrintFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.PrintFtraceEvent.class, perfetto.protos.PrintFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int IP_FIELD_NUMBER = 1;
  private long ip_ = 0L;
  /**
   * <code>optional uint64 ip = 1;</code>
   * @return Whether the ip field is set.
   */
  @java.lang.Override
  public boolean hasIp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 ip = 1;</code>
   * @return The ip.
   */
  @java.lang.Override
  public long getIp() {
    return ip_;
  }

  public static final int BUF_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object buf_ = "";
  /**
   * <code>optional string buf = 2;</code>
   * @return Whether the buf field is set.
   */
  @java.lang.Override
  public boolean hasBuf() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string buf = 2;</code>
   * @return The buf.
   */
  @java.lang.Override
  public java.lang.String getBuf() {
    java.lang.Object ref = buf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        buf_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string buf = 2;</code>
   * @return The bytes for buf.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBufBytes() {
    java.lang.Object ref = buf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, ip_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, buf_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, ip_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, buf_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.PrintFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.PrintFtraceEvent other = (perfetto.protos.PrintFtraceEvent) obj;

    if (hasIp() != other.hasIp()) return false;
    if (hasIp()) {
      if (getIp()
          != other.getIp()) return false;
    }
    if (hasBuf() != other.hasBuf()) return false;
    if (hasBuf()) {
      if (!getBuf()
          .equals(other.getBuf())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIp()) {
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIp());
    }
    if (hasBuf()) {
      hash = (37 * hash) + BUF_FIELD_NUMBER;
      hash = (53 * hash) + getBuf().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.PrintFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.PrintFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.PrintFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.PrintFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.PrintFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.PrintFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.PrintFtraceEvent)
      perfetto.protos.PrintFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_PrintFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_PrintFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.PrintFtraceEvent.class, perfetto.protos.PrintFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.PrintFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ip_ = 0L;
      buf_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_PrintFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.PrintFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.PrintFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.PrintFtraceEvent build() {
      perfetto.protos.PrintFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.PrintFtraceEvent buildPartial() {
      perfetto.protos.PrintFtraceEvent result = new perfetto.protos.PrintFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.PrintFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ip_ = ip_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.buf_ = buf_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.PrintFtraceEvent) {
        return mergeFrom((perfetto.protos.PrintFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.PrintFtraceEvent other) {
      if (other == perfetto.protos.PrintFtraceEvent.getDefaultInstance()) return this;
      if (other.hasIp()) {
        setIp(other.getIp());
      }
      if (other.hasBuf()) {
        buf_ = other.buf_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ip_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              buf_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long ip_ ;
    /**
     * <code>optional uint64 ip = 1;</code>
     * @return Whether the ip field is set.
     */
    @java.lang.Override
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 ip = 1;</code>
     * @return The ip.
     */
    @java.lang.Override
    public long getIp() {
      return ip_;
    }
    /**
     * <code>optional uint64 ip = 1;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(long value) {
      
      ip_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 ip = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ip_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object buf_ = "";
    /**
     * <code>optional string buf = 2;</code>
     * @return Whether the buf field is set.
     */
    public boolean hasBuf() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string buf = 2;</code>
     * @return The buf.
     */
    public java.lang.String getBuf() {
      java.lang.Object ref = buf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          buf_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string buf = 2;</code>
     * @return The bytes for buf.
     */
    public com.google.protobuf.ByteString
        getBufBytes() {
      java.lang.Object ref = buf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string buf = 2;</code>
     * @param value The buf to set.
     * @return This builder for chaining.
     */
    public Builder setBuf(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      buf_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string buf = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuf() {
      buf_ = getDefaultInstance().getBuf();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string buf = 2;</code>
     * @param value The bytes for buf to set.
     * @return This builder for chaining.
     */
    public Builder setBufBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      buf_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.PrintFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.PrintFtraceEvent)
  private static final perfetto.protos.PrintFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.PrintFtraceEvent();
  }

  public static perfetto.protos.PrintFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PrintFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<PrintFtraceEvent>() {
    @java.lang.Override
    public PrintFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PrintFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PrintFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.PrintFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

