// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.SdeSdePerfUpdateBusFtraceEvent}
 */
public final class SdeSdePerfUpdateBusFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.SdeSdePerfUpdateBusFtraceEvent)
    SdeSdePerfUpdateBusFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SdeSdePerfUpdateBusFtraceEvent.newBuilder() to construct.
  private SdeSdePerfUpdateBusFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SdeSdePerfUpdateBusFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SdeSdePerfUpdateBusFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_SdeSdePerfUpdateBusFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_SdeSdePerfUpdateBusFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.class, perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int AB_QUOTA_FIELD_NUMBER = 1;
  private long abQuota_ = 0L;
  /**
   * <code>optional uint64 ab_quota = 1;</code>
   * @return Whether the abQuota field is set.
   */
  @java.lang.Override
  public boolean hasAbQuota() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 ab_quota = 1;</code>
   * @return The abQuota.
   */
  @java.lang.Override
  public long getAbQuota() {
    return abQuota_;
  }

  public static final int BUS_ID_FIELD_NUMBER = 2;
  private int busId_ = 0;
  /**
   * <code>optional uint32 bus_id = 2;</code>
   * @return Whether the busId field is set.
   */
  @java.lang.Override
  public boolean hasBusId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint32 bus_id = 2;</code>
   * @return The busId.
   */
  @java.lang.Override
  public int getBusId() {
    return busId_;
  }

  public static final int CLIENT_FIELD_NUMBER = 3;
  private int client_ = 0;
  /**
   * <code>optional int32 client = 3;</code>
   * @return Whether the client field is set.
   */
  @java.lang.Override
  public boolean hasClient() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 client = 3;</code>
   * @return The client.
   */
  @java.lang.Override
  public int getClient() {
    return client_;
  }

  public static final int IB_QUOTA_FIELD_NUMBER = 4;
  private long ibQuota_ = 0L;
  /**
   * <code>optional uint64 ib_quota = 4;</code>
   * @return Whether the ibQuota field is set.
   */
  @java.lang.Override
  public boolean hasIbQuota() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint64 ib_quota = 4;</code>
   * @return The ibQuota.
   */
  @java.lang.Override
  public long getIbQuota() {
    return ibQuota_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, abQuota_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, busId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, client_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(4, ibQuota_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, abQuota_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, busId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, client_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, ibQuota_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.SdeSdePerfUpdateBusFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.SdeSdePerfUpdateBusFtraceEvent other = (perfetto.protos.SdeSdePerfUpdateBusFtraceEvent) obj;

    if (hasAbQuota() != other.hasAbQuota()) return false;
    if (hasAbQuota()) {
      if (getAbQuota()
          != other.getAbQuota()) return false;
    }
    if (hasBusId() != other.hasBusId()) return false;
    if (hasBusId()) {
      if (getBusId()
          != other.getBusId()) return false;
    }
    if (hasClient() != other.hasClient()) return false;
    if (hasClient()) {
      if (getClient()
          != other.getClient()) return false;
    }
    if (hasIbQuota() != other.hasIbQuota()) return false;
    if (hasIbQuota()) {
      if (getIbQuota()
          != other.getIbQuota()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAbQuota()) {
      hash = (37 * hash) + AB_QUOTA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAbQuota());
    }
    if (hasBusId()) {
      hash = (37 * hash) + BUS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBusId();
    }
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient();
    }
    if (hasIbQuota()) {
      hash = (37 * hash) + IB_QUOTA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIbQuota());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.SdeSdePerfUpdateBusFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.SdeSdePerfUpdateBusFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.SdeSdePerfUpdateBusFtraceEvent)
      perfetto.protos.SdeSdePerfUpdateBusFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_SdeSdePerfUpdateBusFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_SdeSdePerfUpdateBusFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.class, perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      abQuota_ = 0L;
      busId_ = 0;
      client_ = 0;
      ibQuota_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_SdeSdePerfUpdateBusFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.SdeSdePerfUpdateBusFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.SdeSdePerfUpdateBusFtraceEvent build() {
      perfetto.protos.SdeSdePerfUpdateBusFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.SdeSdePerfUpdateBusFtraceEvent buildPartial() {
      perfetto.protos.SdeSdePerfUpdateBusFtraceEvent result = new perfetto.protos.SdeSdePerfUpdateBusFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.SdeSdePerfUpdateBusFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.abQuota_ = abQuota_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.busId_ = busId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.client_ = client_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ibQuota_ = ibQuota_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.SdeSdePerfUpdateBusFtraceEvent) {
        return mergeFrom((perfetto.protos.SdeSdePerfUpdateBusFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.SdeSdePerfUpdateBusFtraceEvent other) {
      if (other == perfetto.protos.SdeSdePerfUpdateBusFtraceEvent.getDefaultInstance()) return this;
      if (other.hasAbQuota()) {
        setAbQuota(other.getAbQuota());
      }
      if (other.hasBusId()) {
        setBusId(other.getBusId());
      }
      if (other.hasClient()) {
        setClient(other.getClient());
      }
      if (other.hasIbQuota()) {
        setIbQuota(other.getIbQuota());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              abQuota_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              busId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              client_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              ibQuota_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long abQuota_ ;
    /**
     * <code>optional uint64 ab_quota = 1;</code>
     * @return Whether the abQuota field is set.
     */
    @java.lang.Override
    public boolean hasAbQuota() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 ab_quota = 1;</code>
     * @return The abQuota.
     */
    @java.lang.Override
    public long getAbQuota() {
      return abQuota_;
    }
    /**
     * <code>optional uint64 ab_quota = 1;</code>
     * @param value The abQuota to set.
     * @return This builder for chaining.
     */
    public Builder setAbQuota(long value) {
      
      abQuota_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 ab_quota = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAbQuota() {
      bitField0_ = (bitField0_ & ~0x00000001);
      abQuota_ = 0L;
      onChanged();
      return this;
    }

    private int busId_ ;
    /**
     * <code>optional uint32 bus_id = 2;</code>
     * @return Whether the busId field is set.
     */
    @java.lang.Override
    public boolean hasBusId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 bus_id = 2;</code>
     * @return The busId.
     */
    @java.lang.Override
    public int getBusId() {
      return busId_;
    }
    /**
     * <code>optional uint32 bus_id = 2;</code>
     * @param value The busId to set.
     * @return This builder for chaining.
     */
    public Builder setBusId(int value) {
      
      busId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 bus_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBusId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      busId_ = 0;
      onChanged();
      return this;
    }

    private int client_ ;
    /**
     * <code>optional int32 client = 3;</code>
     * @return Whether the client field is set.
     */
    @java.lang.Override
    public boolean hasClient() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 client = 3;</code>
     * @return The client.
     */
    @java.lang.Override
    public int getClient() {
      return client_;
    }
    /**
     * <code>optional int32 client = 3;</code>
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(int value) {
      
      client_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 client = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {
      bitField0_ = (bitField0_ & ~0x00000004);
      client_ = 0;
      onChanged();
      return this;
    }

    private long ibQuota_ ;
    /**
     * <code>optional uint64 ib_quota = 4;</code>
     * @return Whether the ibQuota field is set.
     */
    @java.lang.Override
    public boolean hasIbQuota() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 ib_quota = 4;</code>
     * @return The ibQuota.
     */
    @java.lang.Override
    public long getIbQuota() {
      return ibQuota_;
    }
    /**
     * <code>optional uint64 ib_quota = 4;</code>
     * @param value The ibQuota to set.
     * @return This builder for chaining.
     */
    public Builder setIbQuota(long value) {
      
      ibQuota_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 ib_quota = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIbQuota() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ibQuota_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.SdeSdePerfUpdateBusFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.SdeSdePerfUpdateBusFtraceEvent)
  private static final perfetto.protos.SdeSdePerfUpdateBusFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.SdeSdePerfUpdateBusFtraceEvent();
  }

  public static perfetto.protos.SdeSdePerfUpdateBusFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SdeSdePerfUpdateBusFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<SdeSdePerfUpdateBusFtraceEvent>() {
    @java.lang.Override
    public SdeSdePerfUpdateBusFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SdeSdePerfUpdateBusFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SdeSdePerfUpdateBusFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.SdeSdePerfUpdateBusFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

