// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * <pre>
 * Packet emitted by the chromium in-process signal-based callstack sampler.
 * Represents a series of individual stack samples (sampled at discrete points
 * in time), rather than aggregated over an interval.
 * </pre>
 *
 * Protobuf type {@code perfetto.protos.StreamingProfilePacket}
 */
public final class StreamingProfilePacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.StreamingProfilePacket)
    StreamingProfilePacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingProfilePacket.newBuilder() to construct.
  private StreamingProfilePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingProfilePacket() {
    callstackIid_ = emptyLongList();
    timestampDeltaUs_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamingProfilePacket();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_StreamingProfilePacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_StreamingProfilePacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.StreamingProfilePacket.class, perfetto.protos.StreamingProfilePacket.Builder.class);
  }

  private int bitField0_;
  public static final int CALLSTACK_IID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList callstackIid_;
  /**
   * <pre>
   * Index into InternedData.callstacks
   * </pre>
   *
   * <code>repeated uint64 callstack_iid = 1;</code>
   * @return A list containing the callstackIid.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getCallstackIidList() {
    return callstackIid_;
  }
  /**
   * <pre>
   * Index into InternedData.callstacks
   * </pre>
   *
   * <code>repeated uint64 callstack_iid = 1;</code>
   * @return The count of callstackIid.
   */
  public int getCallstackIidCount() {
    return callstackIid_.size();
  }
  /**
   * <pre>
   * Index into InternedData.callstacks
   * </pre>
   *
   * <code>repeated uint64 callstack_iid = 1;</code>
   * @param index The index of the element to return.
   * @return The callstackIid at the given index.
   */
  public long getCallstackIid(int index) {
    return callstackIid_.getLong(index);
  }

  public static final int TIMESTAMP_DELTA_US_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList timestampDeltaUs_;
  /**
   * <pre>
   * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
   * this with ClockSnapshot-based delta encoding instead.
   * </pre>
   *
   * <code>repeated int64 timestamp_delta_us = 2;</code>
   * @return A list containing the timestampDeltaUs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getTimestampDeltaUsList() {
    return timestampDeltaUs_;
  }
  /**
   * <pre>
   * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
   * this with ClockSnapshot-based delta encoding instead.
   * </pre>
   *
   * <code>repeated int64 timestamp_delta_us = 2;</code>
   * @return The count of timestampDeltaUs.
   */
  public int getTimestampDeltaUsCount() {
    return timestampDeltaUs_.size();
  }
  /**
   * <pre>
   * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
   * this with ClockSnapshot-based delta encoding instead.
   * </pre>
   *
   * <code>repeated int64 timestamp_delta_us = 2;</code>
   * @param index The index of the element to return.
   * @return The timestampDeltaUs at the given index.
   */
  public long getTimestampDeltaUs(int index) {
    return timestampDeltaUs_.getLong(index);
  }

  public static final int PROCESS_PRIORITY_FIELD_NUMBER = 3;
  private int processPriority_ = 0;
  /**
   * <code>optional int32 process_priority = 3;</code>
   * @return Whether the processPriority field is set.
   */
  @java.lang.Override
  public boolean hasProcessPriority() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 process_priority = 3;</code>
   * @return The processPriority.
   */
  @java.lang.Override
  public int getProcessPriority() {
    return processPriority_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < callstackIid_.size(); i++) {
      output.writeUInt64(1, callstackIid_.getLong(i));
    }
    for (int i = 0; i < timestampDeltaUs_.size(); i++) {
      output.writeInt64(2, timestampDeltaUs_.getLong(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(3, processPriority_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < callstackIid_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(callstackIid_.getLong(i));
      }
      size += dataSize;
      size += 1 * getCallstackIidList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < timestampDeltaUs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(timestampDeltaUs_.getLong(i));
      }
      size += dataSize;
      size += 1 * getTimestampDeltaUsList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, processPriority_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.StreamingProfilePacket)) {
      return super.equals(obj);
    }
    perfetto.protos.StreamingProfilePacket other = (perfetto.protos.StreamingProfilePacket) obj;

    if (!getCallstackIidList()
        .equals(other.getCallstackIidList())) return false;
    if (!getTimestampDeltaUsList()
        .equals(other.getTimestampDeltaUsList())) return false;
    if (hasProcessPriority() != other.hasProcessPriority()) return false;
    if (hasProcessPriority()) {
      if (getProcessPriority()
          != other.getProcessPriority()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCallstackIidCount() > 0) {
      hash = (37 * hash) + CALLSTACK_IID_FIELD_NUMBER;
      hash = (53 * hash) + getCallstackIidList().hashCode();
    }
    if (getTimestampDeltaUsCount() > 0) {
      hash = (37 * hash) + TIMESTAMP_DELTA_US_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampDeltaUsList().hashCode();
    }
    if (hasProcessPriority()) {
      hash = (37 * hash) + PROCESS_PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getProcessPriority();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.StreamingProfilePacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.StreamingProfilePacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.StreamingProfilePacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.StreamingProfilePacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.StreamingProfilePacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Packet emitted by the chromium in-process signal-based callstack sampler.
   * Represents a series of individual stack samples (sampled at discrete points
   * in time), rather than aggregated over an interval.
   * </pre>
   *
   * Protobuf type {@code perfetto.protos.StreamingProfilePacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.StreamingProfilePacket)
      perfetto.protos.StreamingProfilePacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_StreamingProfilePacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_StreamingProfilePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.StreamingProfilePacket.class, perfetto.protos.StreamingProfilePacket.Builder.class);
    }

    // Construct using perfetto.protos.StreamingProfilePacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      callstackIid_ = emptyLongList();
      timestampDeltaUs_ = emptyLongList();
      processPriority_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_StreamingProfilePacket_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.StreamingProfilePacket getDefaultInstanceForType() {
      return perfetto.protos.StreamingProfilePacket.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.StreamingProfilePacket build() {
      perfetto.protos.StreamingProfilePacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.StreamingProfilePacket buildPartial() {
      perfetto.protos.StreamingProfilePacket result = new perfetto.protos.StreamingProfilePacket(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(perfetto.protos.StreamingProfilePacket result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        callstackIid_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.callstackIid_ = callstackIid_;
      if (((bitField0_ & 0x00000002) != 0)) {
        timestampDeltaUs_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.timestampDeltaUs_ = timestampDeltaUs_;
    }

    private void buildPartial0(perfetto.protos.StreamingProfilePacket result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.processPriority_ = processPriority_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.StreamingProfilePacket) {
        return mergeFrom((perfetto.protos.StreamingProfilePacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.StreamingProfilePacket other) {
      if (other == perfetto.protos.StreamingProfilePacket.getDefaultInstance()) return this;
      if (!other.callstackIid_.isEmpty()) {
        if (callstackIid_.isEmpty()) {
          callstackIid_ = other.callstackIid_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCallstackIidIsMutable();
          callstackIid_.addAll(other.callstackIid_);
        }
        onChanged();
      }
      if (!other.timestampDeltaUs_.isEmpty()) {
        if (timestampDeltaUs_.isEmpty()) {
          timestampDeltaUs_ = other.timestampDeltaUs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureTimestampDeltaUsIsMutable();
          timestampDeltaUs_.addAll(other.timestampDeltaUs_);
        }
        onChanged();
      }
      if (other.hasProcessPriority()) {
        setProcessPriority(other.getProcessPriority());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readUInt64();
              ensureCallstackIidIsMutable();
              callstackIid_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureCallstackIidIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                callstackIid_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              long v = input.readInt64();
              ensureTimestampDeltaUsIsMutable();
              timestampDeltaUs_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureTimestampDeltaUsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                timestampDeltaUs_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 24: {
              processPriority_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList callstackIid_ = emptyLongList();
    private void ensureCallstackIidIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        callstackIid_ = mutableCopy(callstackIid_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @return A list containing the callstackIid.
     */
    public java.util.List<java.lang.Long>
        getCallstackIidList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(callstackIid_) : callstackIid_;
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @return The count of callstackIid.
     */
    public int getCallstackIidCount() {
      return callstackIid_.size();
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @param index The index of the element to return.
     * @return The callstackIid at the given index.
     */
    public long getCallstackIid(int index) {
      return callstackIid_.getLong(index);
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @param index The index to set the value at.
     * @param value The callstackIid to set.
     * @return This builder for chaining.
     */
    public Builder setCallstackIid(
        int index, long value) {
      
      ensureCallstackIidIsMutable();
      callstackIid_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @param value The callstackIid to add.
     * @return This builder for chaining.
     */
    public Builder addCallstackIid(long value) {
      
      ensureCallstackIidIsMutable();
      callstackIid_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @param values The callstackIid to add.
     * @return This builder for chaining.
     */
    public Builder addAllCallstackIid(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureCallstackIidIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, callstackIid_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into InternedData.callstacks
     * </pre>
     *
     * <code>repeated uint64 callstack_iid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallstackIid() {
      callstackIid_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList timestampDeltaUs_ = emptyLongList();
    private void ensureTimestampDeltaUsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        timestampDeltaUs_ = mutableCopy(timestampDeltaUs_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @return A list containing the timestampDeltaUs.
     */
    public java.util.List<java.lang.Long>
        getTimestampDeltaUsList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(timestampDeltaUs_) : timestampDeltaUs_;
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @return The count of timestampDeltaUs.
     */
    public int getTimestampDeltaUsCount() {
      return timestampDeltaUs_.size();
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @param index The index of the element to return.
     * @return The timestampDeltaUs at the given index.
     */
    public long getTimestampDeltaUs(int index) {
      return timestampDeltaUs_.getLong(index);
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @param index The index to set the value at.
     * @param value The timestampDeltaUs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampDeltaUs(
        int index, long value) {
      
      ensureTimestampDeltaUsIsMutable();
      timestampDeltaUs_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @param value The timestampDeltaUs to add.
     * @return This builder for chaining.
     */
    public Builder addTimestampDeltaUs(long value) {
      
      ensureTimestampDeltaUsIsMutable();
      timestampDeltaUs_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @param values The timestampDeltaUs to add.
     * @return This builder for chaining.
     */
    public Builder addAllTimestampDeltaUs(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureTimestampDeltaUsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, timestampDeltaUs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TODO(eseckler): ThreadDescriptor-based timestamps are deprecated. Replace
     * this with ClockSnapshot-based delta encoding instead.
     * </pre>
     *
     * <code>repeated int64 timestamp_delta_us = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampDeltaUs() {
      timestampDeltaUs_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private int processPriority_ ;
    /**
     * <code>optional int32 process_priority = 3;</code>
     * @return Whether the processPriority field is set.
     */
    @java.lang.Override
    public boolean hasProcessPriority() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 process_priority = 3;</code>
     * @return The processPriority.
     */
    @java.lang.Override
    public int getProcessPriority() {
      return processPriority_;
    }
    /**
     * <code>optional int32 process_priority = 3;</code>
     * @param value The processPriority to set.
     * @return This builder for chaining.
     */
    public Builder setProcessPriority(int value) {
      
      processPriority_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 process_priority = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessPriority() {
      bitField0_ = (bitField0_ & ~0x00000004);
      processPriority_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.StreamingProfilePacket)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.StreamingProfilePacket)
  private static final perfetto.protos.StreamingProfilePacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.StreamingProfilePacket();
  }

  public static perfetto.protos.StreamingProfilePacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<StreamingProfilePacket>
      PARSER = new com.google.protobuf.AbstractParser<StreamingProfilePacket>() {
    @java.lang.Override
    public StreamingProfilePacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamingProfilePacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamingProfilePacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.StreamingProfilePacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

