// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface TrustyIpcRxFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.TrustyIpcRxFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 buf_id = 1;</code>
   * @return Whether the bufId field is set.
   */
  boolean hasBufId();
  /**
   * <code>optional uint64 buf_id = 1;</code>
   * @return The bufId.
   */
  long getBufId();

  /**
   * <code>optional uint32 chan = 2;</code>
   * @return Whether the chan field is set.
   */
  boolean hasChan();
  /**
   * <code>optional uint32 chan = 2;</code>
   * @return The chan.
   */
  int getChan();

  /**
   * <code>optional string srv_name = 3;</code>
   * @return Whether the srvName field is set.
   */
  boolean hasSrvName();
  /**
   * <code>optional string srv_name = 3;</code>
   * @return The srvName.
   */
  java.lang.String getSrvName();
  /**
   * <code>optional string srv_name = 3;</code>
   * @return The bytes for srvName.
   */
  com.google.protobuf.ByteString
      getSrvNameBytes();
}
