// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface TrustyReclaimMemoryFtraceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.TrustyReclaimMemoryFtraceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
