// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

public interface V8ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:perfetto.protos.V8Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether to log the actual content of scripts (e.g. content of the JS file
   * that was compiled to generate code).
   * ATTENTION: This could considerably increase the size of the resuling trace
   *            file.
   * </pre>
   *
   * <code>optional bool log_script_sources = 1;</code>
   * @return Whether the logScriptSources field is set.
   */
  boolean hasLogScriptSources();
  /**
   * <pre>
   * Whether to log the actual content of scripts (e.g. content of the JS file
   * that was compiled to generate code).
   * ATTENTION: This could considerably increase the size of the resuling trace
   *            file.
   * </pre>
   *
   * <code>optional bool log_script_sources = 1;</code>
   * @return The logScriptSources.
   */
  boolean getLogScriptSources();

  /**
   * <pre>
   * Whether to log the generated code for jitted functions (machine code or
   * bytecode).
   * ATTENTION: This could considerably increase the size of the resuling trace
   *            file.
   * </pre>
   *
   * <code>optional bool log_instructions = 2;</code>
   * @return Whether the logInstructions field is set.
   */
  boolean hasLogInstructions();
  /**
   * <pre>
   * Whether to log the generated code for jitted functions (machine code or
   * bytecode).
   * ATTENTION: This could considerably increase the size of the resuling trace
   *            file.
   * </pre>
   *
   * <code>optional bool log_instructions = 2;</code>
   * @return The logInstructions.
   */
  boolean getLogInstructions();
}
