// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/perfetto_trace.proto

package perfetto.protos;

/**
 * Protobuf type {@code perfetto.protos.Vb2V4l2QbufFtraceEvent}
 */
public final class Vb2V4l2QbufFtraceEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:perfetto.protos.Vb2V4l2QbufFtraceEvent)
    Vb2V4l2QbufFtraceEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Vb2V4l2QbufFtraceEvent.newBuilder() to construct.
  private Vb2V4l2QbufFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Vb2V4l2QbufFtraceEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Vb2V4l2QbufFtraceEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Vb2V4l2QbufFtraceEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Vb2V4l2QbufFtraceEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            perfetto.protos.Vb2V4l2QbufFtraceEvent.class, perfetto.protos.Vb2V4l2QbufFtraceEvent.Builder.class);
  }

  private int bitField0_;
  public static final int FIELD_FIELD_NUMBER = 1;
  private int field_ = 0;
  /**
   * <code>optional uint32 field = 1;</code>
   * @return Whether the field field is set.
   */
  @java.lang.Override
  public boolean hasField() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 field = 1;</code>
   * @return The field.
   */
  @java.lang.Override
  public int getField() {
    return field_;
  }

  public static final int FLAGS_FIELD_NUMBER = 2;
  private int flags_ = 0;
  /**
   * <code>optional uint32 flags = 2;</code>
   * @return Whether the flags field is set.
   */
  @java.lang.Override
  public boolean hasFlags() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint32 flags = 2;</code>
   * @return The flags.
   */
  @java.lang.Override
  public int getFlags() {
    return flags_;
  }

  public static final int MINOR_FIELD_NUMBER = 3;
  private int minor_ = 0;
  /**
   * <code>optional int32 minor = 3;</code>
   * @return Whether the minor field is set.
   */
  @java.lang.Override
  public boolean hasMinor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 minor = 3;</code>
   * @return The minor.
   */
  @java.lang.Override
  public int getMinor() {
    return minor_;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 4;
  private int sequence_ = 0;
  /**
   * <code>optional uint32 sequence = 4;</code>
   * @return Whether the sequence field is set.
   */
  @java.lang.Override
  public boolean hasSequence() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint32 sequence = 4;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public int getSequence() {
    return sequence_;
  }

  public static final int TIMECODE_FLAGS_FIELD_NUMBER = 5;
  private int timecodeFlags_ = 0;
  /**
   * <code>optional uint32 timecode_flags = 5;</code>
   * @return Whether the timecodeFlags field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeFlags() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional uint32 timecode_flags = 5;</code>
   * @return The timecodeFlags.
   */
  @java.lang.Override
  public int getTimecodeFlags() {
    return timecodeFlags_;
  }

  public static final int TIMECODE_FRAMES_FIELD_NUMBER = 6;
  private int timecodeFrames_ = 0;
  /**
   * <code>optional uint32 timecode_frames = 6;</code>
   * @return Whether the timecodeFrames field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeFrames() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional uint32 timecode_frames = 6;</code>
   * @return The timecodeFrames.
   */
  @java.lang.Override
  public int getTimecodeFrames() {
    return timecodeFrames_;
  }

  public static final int TIMECODE_HOURS_FIELD_NUMBER = 7;
  private int timecodeHours_ = 0;
  /**
   * <code>optional uint32 timecode_hours = 7;</code>
   * @return Whether the timecodeHours field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeHours() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint32 timecode_hours = 7;</code>
   * @return The timecodeHours.
   */
  @java.lang.Override
  public int getTimecodeHours() {
    return timecodeHours_;
  }

  public static final int TIMECODE_MINUTES_FIELD_NUMBER = 8;
  private int timecodeMinutes_ = 0;
  /**
   * <code>optional uint32 timecode_minutes = 8;</code>
   * @return Whether the timecodeMinutes field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeMinutes() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional uint32 timecode_minutes = 8;</code>
   * @return The timecodeMinutes.
   */
  @java.lang.Override
  public int getTimecodeMinutes() {
    return timecodeMinutes_;
  }

  public static final int TIMECODE_SECONDS_FIELD_NUMBER = 9;
  private int timecodeSeconds_ = 0;
  /**
   * <code>optional uint32 timecode_seconds = 9;</code>
   * @return Whether the timecodeSeconds field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeSeconds() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional uint32 timecode_seconds = 9;</code>
   * @return The timecodeSeconds.
   */
  @java.lang.Override
  public int getTimecodeSeconds() {
    return timecodeSeconds_;
  }

  public static final int TIMECODE_TYPE_FIELD_NUMBER = 10;
  private int timecodeType_ = 0;
  /**
   * <code>optional uint32 timecode_type = 10;</code>
   * @return Whether the timecodeType field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeType() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional uint32 timecode_type = 10;</code>
   * @return The timecodeType.
   */
  @java.lang.Override
  public int getTimecodeType() {
    return timecodeType_;
  }

  public static final int TIMECODE_USERBITS0_FIELD_NUMBER = 11;
  private int timecodeUserbits0_ = 0;
  /**
   * <code>optional uint32 timecode_userbits0 = 11;</code>
   * @return Whether the timecodeUserbits0 field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeUserbits0() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional uint32 timecode_userbits0 = 11;</code>
   * @return The timecodeUserbits0.
   */
  @java.lang.Override
  public int getTimecodeUserbits0() {
    return timecodeUserbits0_;
  }

  public static final int TIMECODE_USERBITS1_FIELD_NUMBER = 12;
  private int timecodeUserbits1_ = 0;
  /**
   * <code>optional uint32 timecode_userbits1 = 12;</code>
   * @return Whether the timecodeUserbits1 field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeUserbits1() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional uint32 timecode_userbits1 = 12;</code>
   * @return The timecodeUserbits1.
   */
  @java.lang.Override
  public int getTimecodeUserbits1() {
    return timecodeUserbits1_;
  }

  public static final int TIMECODE_USERBITS2_FIELD_NUMBER = 13;
  private int timecodeUserbits2_ = 0;
  /**
   * <code>optional uint32 timecode_userbits2 = 13;</code>
   * @return Whether the timecodeUserbits2 field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeUserbits2() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>optional uint32 timecode_userbits2 = 13;</code>
   * @return The timecodeUserbits2.
   */
  @java.lang.Override
  public int getTimecodeUserbits2() {
    return timecodeUserbits2_;
  }

  public static final int TIMECODE_USERBITS3_FIELD_NUMBER = 14;
  private int timecodeUserbits3_ = 0;
  /**
   * <code>optional uint32 timecode_userbits3 = 14;</code>
   * @return Whether the timecodeUserbits3 field is set.
   */
  @java.lang.Override
  public boolean hasTimecodeUserbits3() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <code>optional uint32 timecode_userbits3 = 14;</code>
   * @return The timecodeUserbits3.
   */
  @java.lang.Override
  public int getTimecodeUserbits3() {
    return timecodeUserbits3_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 15;
  private long timestamp_ = 0L;
  /**
   * <code>optional int64 timestamp = 15;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <code>optional int64 timestamp = 15;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(1, field_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, flags_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, minor_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt32(4, sequence_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeUInt32(5, timecodeFlags_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeUInt32(6, timecodeFrames_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt32(7, timecodeHours_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeUInt32(8, timecodeMinutes_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeUInt32(9, timecodeSeconds_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeUInt32(10, timecodeType_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      output.writeUInt32(11, timecodeUserbits0_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeUInt32(12, timecodeUserbits1_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      output.writeUInt32(13, timecodeUserbits2_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      output.writeUInt32(14, timecodeUserbits3_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      output.writeInt64(15, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, field_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, flags_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, minor_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, sequence_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, timecodeFlags_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, timecodeFrames_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, timecodeHours_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, timecodeMinutes_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, timecodeSeconds_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, timecodeType_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(11, timecodeUserbits0_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(12, timecodeUserbits1_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(13, timecodeUserbits2_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(14, timecodeUserbits3_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof perfetto.protos.Vb2V4l2QbufFtraceEvent)) {
      return super.equals(obj);
    }
    perfetto.protos.Vb2V4l2QbufFtraceEvent other = (perfetto.protos.Vb2V4l2QbufFtraceEvent) obj;

    if (hasField() != other.hasField()) return false;
    if (hasField()) {
      if (getField()
          != other.getField()) return false;
    }
    if (hasFlags() != other.hasFlags()) return false;
    if (hasFlags()) {
      if (getFlags()
          != other.getFlags()) return false;
    }
    if (hasMinor() != other.hasMinor()) return false;
    if (hasMinor()) {
      if (getMinor()
          != other.getMinor()) return false;
    }
    if (hasSequence() != other.hasSequence()) return false;
    if (hasSequence()) {
      if (getSequence()
          != other.getSequence()) return false;
    }
    if (hasTimecodeFlags() != other.hasTimecodeFlags()) return false;
    if (hasTimecodeFlags()) {
      if (getTimecodeFlags()
          != other.getTimecodeFlags()) return false;
    }
    if (hasTimecodeFrames() != other.hasTimecodeFrames()) return false;
    if (hasTimecodeFrames()) {
      if (getTimecodeFrames()
          != other.getTimecodeFrames()) return false;
    }
    if (hasTimecodeHours() != other.hasTimecodeHours()) return false;
    if (hasTimecodeHours()) {
      if (getTimecodeHours()
          != other.getTimecodeHours()) return false;
    }
    if (hasTimecodeMinutes() != other.hasTimecodeMinutes()) return false;
    if (hasTimecodeMinutes()) {
      if (getTimecodeMinutes()
          != other.getTimecodeMinutes()) return false;
    }
    if (hasTimecodeSeconds() != other.hasTimecodeSeconds()) return false;
    if (hasTimecodeSeconds()) {
      if (getTimecodeSeconds()
          != other.getTimecodeSeconds()) return false;
    }
    if (hasTimecodeType() != other.hasTimecodeType()) return false;
    if (hasTimecodeType()) {
      if (getTimecodeType()
          != other.getTimecodeType()) return false;
    }
    if (hasTimecodeUserbits0() != other.hasTimecodeUserbits0()) return false;
    if (hasTimecodeUserbits0()) {
      if (getTimecodeUserbits0()
          != other.getTimecodeUserbits0()) return false;
    }
    if (hasTimecodeUserbits1() != other.hasTimecodeUserbits1()) return false;
    if (hasTimecodeUserbits1()) {
      if (getTimecodeUserbits1()
          != other.getTimecodeUserbits1()) return false;
    }
    if (hasTimecodeUserbits2() != other.hasTimecodeUserbits2()) return false;
    if (hasTimecodeUserbits2()) {
      if (getTimecodeUserbits2()
          != other.getTimecodeUserbits2()) return false;
    }
    if (hasTimecodeUserbits3() != other.hasTimecodeUserbits3()) return false;
    if (hasTimecodeUserbits3()) {
      if (getTimecodeUserbits3()
          != other.getTimecodeUserbits3()) return false;
    }
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (getTimestamp()
          != other.getTimestamp()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasField()) {
      hash = (37 * hash) + FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getField();
    }
    if (hasFlags()) {
      hash = (37 * hash) + FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getFlags();
    }
    if (hasMinor()) {
      hash = (37 * hash) + MINOR_FIELD_NUMBER;
      hash = (53 * hash) + getMinor();
    }
    if (hasSequence()) {
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
    }
    if (hasTimecodeFlags()) {
      hash = (37 * hash) + TIMECODE_FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeFlags();
    }
    if (hasTimecodeFrames()) {
      hash = (37 * hash) + TIMECODE_FRAMES_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeFrames();
    }
    if (hasTimecodeHours()) {
      hash = (37 * hash) + TIMECODE_HOURS_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeHours();
    }
    if (hasTimecodeMinutes()) {
      hash = (37 * hash) + TIMECODE_MINUTES_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeMinutes();
    }
    if (hasTimecodeSeconds()) {
      hash = (37 * hash) + TIMECODE_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeSeconds();
    }
    if (hasTimecodeType()) {
      hash = (37 * hash) + TIMECODE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeType();
    }
    if (hasTimecodeUserbits0()) {
      hash = (37 * hash) + TIMECODE_USERBITS0_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeUserbits0();
    }
    if (hasTimecodeUserbits1()) {
      hash = (37 * hash) + TIMECODE_USERBITS1_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeUserbits1();
    }
    if (hasTimecodeUserbits2()) {
      hash = (37 * hash) + TIMECODE_USERBITS2_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeUserbits2();
    }
    if (hasTimecodeUserbits3()) {
      hash = (37 * hash) + TIMECODE_USERBITS3_FIELD_NUMBER;
      hash = (53 * hash) + getTimecodeUserbits3();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static perfetto.protos.Vb2V4l2QbufFtraceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(perfetto.protos.Vb2V4l2QbufFtraceEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code perfetto.protos.Vb2V4l2QbufFtraceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:perfetto.protos.Vb2V4l2QbufFtraceEvent)
      perfetto.protos.Vb2V4l2QbufFtraceEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Vb2V4l2QbufFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Vb2V4l2QbufFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.Vb2V4l2QbufFtraceEvent.class, perfetto.protos.Vb2V4l2QbufFtraceEvent.Builder.class);
    }

    // Construct using perfetto.protos.Vb2V4l2QbufFtraceEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      field_ = 0;
      flags_ = 0;
      minor_ = 0;
      sequence_ = 0;
      timecodeFlags_ = 0;
      timecodeFrames_ = 0;
      timecodeHours_ = 0;
      timecodeMinutes_ = 0;
      timecodeSeconds_ = 0;
      timecodeType_ = 0;
      timecodeUserbits0_ = 0;
      timecodeUserbits1_ = 0;
      timecodeUserbits2_ = 0;
      timecodeUserbits3_ = 0;
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return perfetto.protos.PerfettoTrace.internal_static_perfetto_protos_Vb2V4l2QbufFtraceEvent_descriptor;
    }

    @java.lang.Override
    public perfetto.protos.Vb2V4l2QbufFtraceEvent getDefaultInstanceForType() {
      return perfetto.protos.Vb2V4l2QbufFtraceEvent.getDefaultInstance();
    }

    @java.lang.Override
    public perfetto.protos.Vb2V4l2QbufFtraceEvent build() {
      perfetto.protos.Vb2V4l2QbufFtraceEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public perfetto.protos.Vb2V4l2QbufFtraceEvent buildPartial() {
      perfetto.protos.Vb2V4l2QbufFtraceEvent result = new perfetto.protos.Vb2V4l2QbufFtraceEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(perfetto.protos.Vb2V4l2QbufFtraceEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.field_ = field_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.flags_ = flags_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minor_ = minor_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sequence_ = sequence_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timecodeFlags_ = timecodeFlags_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timecodeFrames_ = timecodeFrames_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timecodeHours_ = timecodeHours_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.timecodeMinutes_ = timecodeMinutes_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.timecodeSeconds_ = timecodeSeconds_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.timecodeType_ = timecodeType_;
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.timecodeUserbits0_ = timecodeUserbits0_;
        to_bitField0_ |= 0x00000400;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.timecodeUserbits1_ = timecodeUserbits1_;
        to_bitField0_ |= 0x00000800;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.timecodeUserbits2_ = timecodeUserbits2_;
        to_bitField0_ |= 0x00001000;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.timecodeUserbits3_ = timecodeUserbits3_;
        to_bitField0_ |= 0x00002000;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.timestamp_ = timestamp_;
        to_bitField0_ |= 0x00004000;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof perfetto.protos.Vb2V4l2QbufFtraceEvent) {
        return mergeFrom((perfetto.protos.Vb2V4l2QbufFtraceEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(perfetto.protos.Vb2V4l2QbufFtraceEvent other) {
      if (other == perfetto.protos.Vb2V4l2QbufFtraceEvent.getDefaultInstance()) return this;
      if (other.hasField()) {
        setField(other.getField());
      }
      if (other.hasFlags()) {
        setFlags(other.getFlags());
      }
      if (other.hasMinor()) {
        setMinor(other.getMinor());
      }
      if (other.hasSequence()) {
        setSequence(other.getSequence());
      }
      if (other.hasTimecodeFlags()) {
        setTimecodeFlags(other.getTimecodeFlags());
      }
      if (other.hasTimecodeFrames()) {
        setTimecodeFrames(other.getTimecodeFrames());
      }
      if (other.hasTimecodeHours()) {
        setTimecodeHours(other.getTimecodeHours());
      }
      if (other.hasTimecodeMinutes()) {
        setTimecodeMinutes(other.getTimecodeMinutes());
      }
      if (other.hasTimecodeSeconds()) {
        setTimecodeSeconds(other.getTimecodeSeconds());
      }
      if (other.hasTimecodeType()) {
        setTimecodeType(other.getTimecodeType());
      }
      if (other.hasTimecodeUserbits0()) {
        setTimecodeUserbits0(other.getTimecodeUserbits0());
      }
      if (other.hasTimecodeUserbits1()) {
        setTimecodeUserbits1(other.getTimecodeUserbits1());
      }
      if (other.hasTimecodeUserbits2()) {
        setTimecodeUserbits2(other.getTimecodeUserbits2());
      }
      if (other.hasTimecodeUserbits3()) {
        setTimecodeUserbits3(other.getTimecodeUserbits3());
      }
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              field_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              flags_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              minor_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              sequence_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              timecodeFlags_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              timecodeFrames_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              timecodeHours_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              timecodeMinutes_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              timecodeSeconds_ = input.readUInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              timecodeType_ = input.readUInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              timecodeUserbits0_ = input.readUInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              timecodeUserbits1_ = input.readUInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              timecodeUserbits2_ = input.readUInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              timecodeUserbits3_ = input.readUInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int field_ ;
    /**
     * <code>optional uint32 field = 1;</code>
     * @return Whether the field field is set.
     */
    @java.lang.Override
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public int getField() {
      return field_;
    }
    /**
     * <code>optional uint32 field = 1;</code>
     * @param value The field to set.
     * @return This builder for chaining.
     */
    public Builder setField(int value) {
      
      field_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 field = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearField() {
      bitField0_ = (bitField0_ & ~0x00000001);
      field_ = 0;
      onChanged();
      return this;
    }

    private int flags_ ;
    /**
     * <code>optional uint32 flags = 2;</code>
     * @return Whether the flags field is set.
     */
    @java.lang.Override
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 flags = 2;</code>
     * @return The flags.
     */
    @java.lang.Override
    public int getFlags() {
      return flags_;
    }
    /**
     * <code>optional uint32 flags = 2;</code>
     * @param value The flags to set.
     * @return This builder for chaining.
     */
    public Builder setFlags(int value) {
      
      flags_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 flags = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlags() {
      bitField0_ = (bitField0_ & ~0x00000002);
      flags_ = 0;
      onChanged();
      return this;
    }

    private int minor_ ;
    /**
     * <code>optional int32 minor = 3;</code>
     * @return Whether the minor field is set.
     */
    @java.lang.Override
    public boolean hasMinor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 minor = 3;</code>
     * @return The minor.
     */
    @java.lang.Override
    public int getMinor() {
      return minor_;
    }
    /**
     * <code>optional int32 minor = 3;</code>
     * @param value The minor to set.
     * @return This builder for chaining.
     */
    public Builder setMinor(int value) {
      
      minor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 minor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minor_ = 0;
      onChanged();
      return this;
    }

    private int sequence_ ;
    /**
     * <code>optional uint32 sequence = 4;</code>
     * @return Whether the sequence field is set.
     */
    @java.lang.Override
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 sequence = 4;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public int getSequence() {
      return sequence_;
    }
    /**
     * <code>optional uint32 sequence = 4;</code>
     * @param value The sequence to set.
     * @return This builder for chaining.
     */
    public Builder setSequence(int value) {
      
      sequence_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 sequence = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sequence_ = 0;
      onChanged();
      return this;
    }

    private int timecodeFlags_ ;
    /**
     * <code>optional uint32 timecode_flags = 5;</code>
     * @return Whether the timecodeFlags field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeFlags() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 timecode_flags = 5;</code>
     * @return The timecodeFlags.
     */
    @java.lang.Override
    public int getTimecodeFlags() {
      return timecodeFlags_;
    }
    /**
     * <code>optional uint32 timecode_flags = 5;</code>
     * @param value The timecodeFlags to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeFlags(int value) {
      
      timecodeFlags_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_flags = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeFlags() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timecodeFlags_ = 0;
      onChanged();
      return this;
    }

    private int timecodeFrames_ ;
    /**
     * <code>optional uint32 timecode_frames = 6;</code>
     * @return Whether the timecodeFrames field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeFrames() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 timecode_frames = 6;</code>
     * @return The timecodeFrames.
     */
    @java.lang.Override
    public int getTimecodeFrames() {
      return timecodeFrames_;
    }
    /**
     * <code>optional uint32 timecode_frames = 6;</code>
     * @param value The timecodeFrames to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeFrames(int value) {
      
      timecodeFrames_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_frames = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeFrames() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timecodeFrames_ = 0;
      onChanged();
      return this;
    }

    private int timecodeHours_ ;
    /**
     * <code>optional uint32 timecode_hours = 7;</code>
     * @return Whether the timecodeHours field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeHours() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 timecode_hours = 7;</code>
     * @return The timecodeHours.
     */
    @java.lang.Override
    public int getTimecodeHours() {
      return timecodeHours_;
    }
    /**
     * <code>optional uint32 timecode_hours = 7;</code>
     * @param value The timecodeHours to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeHours(int value) {
      
      timecodeHours_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_hours = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeHours() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timecodeHours_ = 0;
      onChanged();
      return this;
    }

    private int timecodeMinutes_ ;
    /**
     * <code>optional uint32 timecode_minutes = 8;</code>
     * @return Whether the timecodeMinutes field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeMinutes() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint32 timecode_minutes = 8;</code>
     * @return The timecodeMinutes.
     */
    @java.lang.Override
    public int getTimecodeMinutes() {
      return timecodeMinutes_;
    }
    /**
     * <code>optional uint32 timecode_minutes = 8;</code>
     * @param value The timecodeMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeMinutes(int value) {
      
      timecodeMinutes_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_minutes = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeMinutes() {
      bitField0_ = (bitField0_ & ~0x00000080);
      timecodeMinutes_ = 0;
      onChanged();
      return this;
    }

    private int timecodeSeconds_ ;
    /**
     * <code>optional uint32 timecode_seconds = 9;</code>
     * @return Whether the timecodeSeconds field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeSeconds() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint32 timecode_seconds = 9;</code>
     * @return The timecodeSeconds.
     */
    @java.lang.Override
    public int getTimecodeSeconds() {
      return timecodeSeconds_;
    }
    /**
     * <code>optional uint32 timecode_seconds = 9;</code>
     * @param value The timecodeSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeSeconds(int value) {
      
      timecodeSeconds_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_seconds = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeSeconds() {
      bitField0_ = (bitField0_ & ~0x00000100);
      timecodeSeconds_ = 0;
      onChanged();
      return this;
    }

    private int timecodeType_ ;
    /**
     * <code>optional uint32 timecode_type = 10;</code>
     * @return Whether the timecodeType field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeType() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional uint32 timecode_type = 10;</code>
     * @return The timecodeType.
     */
    @java.lang.Override
    public int getTimecodeType() {
      return timecodeType_;
    }
    /**
     * <code>optional uint32 timecode_type = 10;</code>
     * @param value The timecodeType to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeType(int value) {
      
      timecodeType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_type = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeType() {
      bitField0_ = (bitField0_ & ~0x00000200);
      timecodeType_ = 0;
      onChanged();
      return this;
    }

    private int timecodeUserbits0_ ;
    /**
     * <code>optional uint32 timecode_userbits0 = 11;</code>
     * @return Whether the timecodeUserbits0 field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeUserbits0() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional uint32 timecode_userbits0 = 11;</code>
     * @return The timecodeUserbits0.
     */
    @java.lang.Override
    public int getTimecodeUserbits0() {
      return timecodeUserbits0_;
    }
    /**
     * <code>optional uint32 timecode_userbits0 = 11;</code>
     * @param value The timecodeUserbits0 to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeUserbits0(int value) {
      
      timecodeUserbits0_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_userbits0 = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeUserbits0() {
      bitField0_ = (bitField0_ & ~0x00000400);
      timecodeUserbits0_ = 0;
      onChanged();
      return this;
    }

    private int timecodeUserbits1_ ;
    /**
     * <code>optional uint32 timecode_userbits1 = 12;</code>
     * @return Whether the timecodeUserbits1 field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeUserbits1() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional uint32 timecode_userbits1 = 12;</code>
     * @return The timecodeUserbits1.
     */
    @java.lang.Override
    public int getTimecodeUserbits1() {
      return timecodeUserbits1_;
    }
    /**
     * <code>optional uint32 timecode_userbits1 = 12;</code>
     * @param value The timecodeUserbits1 to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeUserbits1(int value) {
      
      timecodeUserbits1_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_userbits1 = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeUserbits1() {
      bitField0_ = (bitField0_ & ~0x00000800);
      timecodeUserbits1_ = 0;
      onChanged();
      return this;
    }

    private int timecodeUserbits2_ ;
    /**
     * <code>optional uint32 timecode_userbits2 = 13;</code>
     * @return Whether the timecodeUserbits2 field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeUserbits2() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional uint32 timecode_userbits2 = 13;</code>
     * @return The timecodeUserbits2.
     */
    @java.lang.Override
    public int getTimecodeUserbits2() {
      return timecodeUserbits2_;
    }
    /**
     * <code>optional uint32 timecode_userbits2 = 13;</code>
     * @param value The timecodeUserbits2 to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeUserbits2(int value) {
      
      timecodeUserbits2_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_userbits2 = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeUserbits2() {
      bitField0_ = (bitField0_ & ~0x00001000);
      timecodeUserbits2_ = 0;
      onChanged();
      return this;
    }

    private int timecodeUserbits3_ ;
    /**
     * <code>optional uint32 timecode_userbits3 = 14;</code>
     * @return Whether the timecodeUserbits3 field is set.
     */
    @java.lang.Override
    public boolean hasTimecodeUserbits3() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional uint32 timecode_userbits3 = 14;</code>
     * @return The timecodeUserbits3.
     */
    @java.lang.Override
    public int getTimecodeUserbits3() {
      return timecodeUserbits3_;
    }
    /**
     * <code>optional uint32 timecode_userbits3 = 14;</code>
     * @param value The timecodeUserbits3 to set.
     * @return This builder for chaining.
     */
    public Builder setTimecodeUserbits3(int value) {
      
      timecodeUserbits3_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 timecode_userbits3 = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimecodeUserbits3() {
      bitField0_ = (bitField0_ & ~0x00002000);
      timecodeUserbits3_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>optional int64 timestamp = 15;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional int64 timestamp = 15;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional int64 timestamp = 15;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 timestamp = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00004000);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:perfetto.protos.Vb2V4l2QbufFtraceEvent)
  }

  // @@protoc_insertion_point(class_scope:perfetto.protos.Vb2V4l2QbufFtraceEvent)
  private static final perfetto.protos.Vb2V4l2QbufFtraceEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new perfetto.protos.Vb2V4l2QbufFtraceEvent();
  }

  public static perfetto.protos.Vb2V4l2QbufFtraceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Vb2V4l2QbufFtraceEvent>
      PARSER = new com.google.protobuf.AbstractParser<Vb2V4l2QbufFtraceEvent>() {
    @java.lang.Override
    public Vb2V4l2QbufFtraceEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Vb2V4l2QbufFtraceEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vb2V4l2QbufFtraceEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public perfetto.protos.Vb2V4l2QbufFtraceEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

